-- ⚠️운영(도우제조원가시스템) 배포용. dev(DWCMSTEST) 라이브 정의에서 추출(2026-08-28).
-- 검토 후 운영에서 실행. 멱등(존재시 스킵/ALTER).

-- 인터페이스 스테이징 26종

IF OBJECT_ID(N'dbo.DOI_HQ_IF_ACCOUNT', N'U') IS NULL
CREATE TABLE dbo.DOI_HQ_IF_ACCOUNT (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [LOAD_DTTM] datetime NOT NULL,
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [SMAccKind] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccSeq] int NULL,
    [AccNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [DualAccNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMAccKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccLevel] int NULL,
    [UpperAccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UpperAccSeq] int NULL,
    [TreeSort] int NULL,
    [AccSort] int NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_HQ_IF_DEPT', N'U') IS NULL
CREATE TABLE dbo.DOI_HQ_IF_DEPT (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NULL,
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [CCtrName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMCCtrKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMCostTypeName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AccUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMCourceTypeName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RegDate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RegUserName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsNotUse] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsNotUseDate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DispSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CCtrSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMCostType] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RegUserSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnit] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AccUnit] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMCourceType] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMCCtrKind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsTemp] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [LastUserName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [LastDateTime] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy1] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy2] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy3] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy4] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy5] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy6] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy7] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy8] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy9] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy10] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_HQ_IF_DEPT_COST', N'U') IS NULL
CREATE TABLE dbo.DOI_HQ_IF_DEPT_COST (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL,
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [CCtrName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptSeq] int NULL,
    [AccNameCost] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMCostTypeName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccSeq] int NULL,
    [DrAmt] decimal(19,5) NULL,
    [CrAmt] decimal(19,5) NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL,
    [UMCCtrKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMSourceTypeName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CCtrAccUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_HQ_IF_EXP_INVOICE', N'U') IS NULL
CREATE TABLE dbo.DOI_HQ_IF_EXP_INVOICE (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NULL,
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NULL,
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceSerl] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsDelvCfm] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnit] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceDate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceRefNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMExpKind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMOutKind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMOutKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMExpKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurrSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurrName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMPriceTerm] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMPriceTermName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ExRate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Qty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Price] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemPrice] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustPrice] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [VATRate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurVAT] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DomAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DomVAT] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [TotDomAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RemarkM] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [StdUnitSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [StdUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [StdQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [WHName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DVPlaceSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DVPlaceName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMProgressTypeName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsStockSales] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsSalesProc] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsReturn] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsWithSalesVat] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMEtcOutKind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMEtcOutKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [LotNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [GrossWeight] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [NetWeight] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Volume] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Capacity] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ContainerNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CottonNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SerialNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SalesPrice] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassSSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassSName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassMSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassMName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassLSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassLName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [PONo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SourceRefNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SourceNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy1] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy2] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy3] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy4] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy5] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy6] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy7] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy8] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy9] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy10] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustItemSpec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemEngName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AddInfo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemDVDate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMSalesProgTypeName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [WHSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EndUser] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EndUserText] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EndUserName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [HSCode] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BKCustName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [NonSalesAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [NonSalesQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_HQ_IF_MATERIAL', N'U') IS NULL
CREATE TABLE dbo.DOI_HQ_IF_MATERIAL (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NULL,
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ProcRev] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ProcSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ProcName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyItemSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssySpec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyUnitSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyQtyNumerator] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyQtyDenominator] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatItemSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatSpec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatUnitSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [STDUnitSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [StdUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatQtyNum] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatQtyDen] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [STDQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InLossRate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InLossMatQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [OutLossRate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [OutLossMatQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [LastUserSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [LastDateTime] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Memo1] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Memo2] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Memo3] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMDelvType] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMDelvTypeName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnit] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UptEmpSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UptEmpName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UptDate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Location] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MasterRemark] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SubItemProcRev] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UserNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSerl] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RegEmpName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RegDate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassLName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassMName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatAssetName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatUMItemClassLName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatUMItemClassMName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatUMItemClassName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [TimeUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [WorkHour] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MESProcSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MESProcName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_HQ_IF_SALES', N'U') IS NULL
CREATE TABLE dbo.DOI_HQ_IF_SALES (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NULL,
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NULL,
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceDate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceSerl] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMExpKind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMExpKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMOutKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsStockSales] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsConsign] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustPrice] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Qty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsInclusedVAT] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [VATRate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurrSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurrName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ExRate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Price] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurVAT] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [TotCurAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DomAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DomVAT] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [TotDomAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [STDUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [STDQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [WHName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RemarkM] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RemarkI] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMProgressTypeName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsDelvCfm] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMSalesCrtKind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMSalesCrtKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BillCustSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BillCustName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SourceNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SourceRefNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsReturn] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SalesQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SalesPrice] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustItemSpec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMEtcOutKind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMEtcOutKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [LotNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DVCondition] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DVPlace] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DVPlaceName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BillAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMTransStatusName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassSName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassMName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassLName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BKCustName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy1] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy2] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy3] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy4] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy5] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy6] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy7] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy8] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy9] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Dummy10] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsRetroactivity] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RetroactivityQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ChannelName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Location] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [PONo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BizAddr] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SetInOutNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BizNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemDvDate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_HQ_IF_STOCK_DETAIL', N'U') IS NULL
CREATE TABLE dbo.DOI_HQ_IF_STOCK_DETAIL (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL,
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassSSeq] int NULL,
    [UMItemClassMSeq] int NULL,
    [UMItemClassLSeq] int NULL,
    [UMItemClassSName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItmeClassMName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassLName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemEtcClassSeq] int NULL,
    [UMItemEtcClassName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] int NULL,
    [AssetName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [PreQty] decimal(19,5) NULL,
    [PreAmt] decimal(19,5) NULL,
    [ProdQty] decimal(19,5) NULL,
    [ProdAmt] decimal(19,5) NULL,
    [BuyQty] decimal(19,5) NULL,
    [BuyAmt] decimal(19,5) NULL,
    [MvInQty] decimal(19,5) NULL,
    [MvInAmt] decimal(19,5) NULL,
    [EtcInQty] decimal(19,5) NULL,
    [EtcInAmt] decimal(19,5) NULL,
    [ExchangeInQty] decimal(19,5) NULL,
    [ExchangeInAmt] decimal(19,5) NULL,
    [SalesQty] decimal(19,5) NULL,
    [SalesAmt] decimal(19,5) NULL,
    [InputQty] decimal(19,5) NULL,
    [InputAmt] decimal(19,5) NULL,
    [PJTOutQty] decimal(19,5) NULL,
    [PJTOutAmt] decimal(19,5) NULL,
    [MvOutQty] decimal(19,5) NULL,
    [MvOutAmt] decimal(19,5) NULL,
    [EtcOutQty] decimal(19,5) NULL,
    [EtcOutAmt] decimal(19,5) NULL,
    [ExchangeOutQty] decimal(19,5) NULL,
    [ExchangeOutAmt] decimal(19,5) NULL,
    [InQty] decimal(19,5) NULL,
    [OutAmt] decimal(19,5) NULL,
    [InAmt] decimal(19,5) NULL,
    [StockQty] decimal(19,5) NULL,
    [OutQty] decimal(19,5) NULL,
    [StockAmt] decimal(19,5) NULL,
    [StockQty2] decimal(19,5) NULL,
    [StockAmt2] decimal(19,5) NULL,
    [DiffQty] decimal(19,5) NULL,
    [DiffAmt] decimal(19,5) NULL,
    [DivPrice] decimal(19,5) NULL,
    [StkPrice] decimal(19,5) NULL,
    [InputAccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SalesAccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetGroupName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetAccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_HQ_IF_WH_STOCK_SUM', N'U') IS NULL
CREATE TABLE dbo.DOI_HQ_IF_WH_STOCK_SUM (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL,
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [SMAssetGrpName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [WHName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMWHKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassLName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassMName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassSName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMStatusName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [PrevQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [OutQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [StockQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [WHSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMWHKind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Location] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SafetyQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CostWHName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsLot] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_ACCLANG', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_ACCLANG (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [FSItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [FSItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RowIDX] int NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_ACCOUNT', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_ACCOUNT (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [SMAccKind] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccSeq] int NULL,
    [AccNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [DualAccNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMAccKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccLevel] int NULL,
    [UpperAccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UpperAccSeq] int NULL,
    [TreeSort] int NULL,
    [AccSort] int NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_BIZ_STOCK_SUM', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_BIZ_STOCK_SUM (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [Title] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [TitleSeq] int NULL,
    [Title2] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [TitleSeq2] int NULL,
    [BizUnit] int NULL,
    [BizUnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMAssetGrpName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassLName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassMName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassSName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMStatusName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] int NULL,
    [UnitSeq] int NULL,
    [PrevQty] decimal(19,5) NULL,
    [InQty] decimal(19,5) NULL,
    [OutQty] decimal(19,5) NULL,
    [StockQty] decimal(19,5) NULL,
    [RowIDX] int NULL,
    [ColIDX] int NULL,
    [Qty] decimal(19,5) NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_DEPT', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_DEPT (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [EngDeptName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [BegDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [EndDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnit] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [FactUnit] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(1000) COLLATE Korean_Wansung_CI_AS NULL,
    [IsUse] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [CCtrName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMDeptAttrName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Email] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_DEPT_COST', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_DEPT_COST (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [CCtrName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptSeq] int NULL,
    [AccNameCost] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMCostTypeName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccSeq] int NULL,
    [DrAmt] decimal(19,5) NULL,
    [CrAmt] decimal(19,5) NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_ETC_INOUT', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_ETC_INOUT (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [InOutDate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InOutName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMEtcOutKindSource] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMEtcOutKindDetail] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassLName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassMName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassSName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMAdjustKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EtcOutQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EtcOutAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EtcOutPrice] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AccName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [WHName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemRemark] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_EXP_CLAIM', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_EXP_CLAIM (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnit] int NULL,
    [ClaimNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ClaimSeq] int NULL,
    [ClaimSerl] int NULL,
    [ClaimDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [SMExpKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMOutKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMConsignKind] int NULL,
    [SMConsignKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [CustName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [CustSeq] int NULL,
    [CustNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [CurrSeq] int NULL,
    [CurrName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ExRate] decimal(19,5) NULL,
    [ItemSeq] int NULL,
    [ItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitSeq] int NULL,
    [UnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Qty] decimal(19,5) NULL,
    [Price] decimal(19,5) NULL,
    [ItemPrice] decimal(19,5) NULL,
    [CustPrice] decimal(19,5) NULL,
    [VATRate] decimal(19,5) NULL,
    [CurAmt] decimal(19,5) NULL,
    [CurVAT] decimal(19,5) NULL,
    [DomAmt] decimal(19,5) NULL,
    [DomVAT] decimal(19,5) NULL,
    [StdUnitSeq] int NULL,
    [StdUnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [StdQty] decimal(19,5) NULL,
    [BKCustName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [DVDateM] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [BLDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [BLNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [BLRefNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [PermitDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [PermitNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [PermitRefNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SalesNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SlipID] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMProgressReturnTypeName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMProgressTypeName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMExpKind] int NULL,
    [SlipSeq] int NULL,
    [SourceNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SourceRefNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ISPJT] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [LotNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RemarkM] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Memo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [LastUserName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [LastDateTime] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [WHName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [BLPrice] decimal(19,5) NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_EXP_PERMIT', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_EXP_PERMIT (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnit] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [PermitDate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [PermitNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [PermitRefNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMExpKind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMExpKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CustNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurrSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurrName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMPriceTerms] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMPriceTermsName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [PermitType] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [PermitTypeName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ExRate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Qty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [FOBPrice] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DomPrice] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CurAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [DomAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [FOBDomAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RemarkI] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMEtcOutkind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UMEtcOutkindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMProgressTypeName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SalesAmt] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceRefNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SourceNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SourceRefNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMSalesProgTypeName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_EXP_SALES', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_EXP_SALES (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnit] int NULL,
    [BizUnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMExpKind] int NULL,
    [SMExpKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptSeq] int NULL,
    [DeptName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpSeq] int NULL,
    [EmpName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [CustSeq] int NULL,
    [CustName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] int NULL,
    [ItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitSeq] int NULL,
    [UnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemPrice] decimal(19,5) NULL,
    [CustPrice] decimal(19,5) NULL,
    [Qty] decimal(19,5) NULL,
    [Price] decimal(19,5) NULL,
    [CurAmt] decimal(19,5) NULL,
    [DomAmt] decimal(19,5) NULL,
    [WHSeq] int NULL,
    [WHName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RemarkM] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AccSeq] int NULL,
    [AccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMPriceTerms] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMPriceTermsName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [CurrName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ExRate] decimal(19,5) NULL,
    [RemarkI] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceRefNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMChannelName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [InvoiceDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_FG_SUBUL', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_FG_SUBUL (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [factory] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [work_date] varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [mat_id] varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
    [boh_ok_mes] int NULL,
    [normal_last_month] int NULL,
    [normal_this_month] int NULL,
    [backship_sorting] int NULL,
    [backship_pfrw] int NULL,
    [backship_plrw] int NULL,
    [wh_rt_sorting] int NULL,
    [wh_rt_pfrw] int NULL,
    [wh_rt_plrw] int NULL,
    [etc_input] int NULL,
    [back_ship_ng_qty] int NULL,
    [total_wh_input] int NULL,
    [other_input_total] int NULL,
    [shipped_level_a_paid] int NULL,
    [shipped_level_a_free] int NULL,
    [shipped_level_b_paid] int NULL,
    [shipped_level_b_free] int NULL,
    [t_output_3] int NULL,
    [line_transfer_total] int NULL,
    [etc_output] int NULL,
    [line_transfer_rework] int NULL,
    [line_transfer_sorting] int NULL,
    [other_output_total] int NULL,
    [total_out_qty] int NULL,
    [eoh_ok_mes] int NULL,
    [loss_spare] int NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_ITEM', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_ITEM (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] int NULL,
    [ItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [TrunName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetSeq] int NULL,
    [UnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitSeq] int NULL,
    [SMABC] int NULL,
    [SMABCName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMStatus] int NULL,
    [SMStatusName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMInOutKind] int NULL,
    [SMInOutKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptSeq] int NULL,
    [EmpName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpSeq] int NULL,
    [STDItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [STDItemSeq] int NULL,
    [ItemEngName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassLName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassMName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassSName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClass] int NULL,
    [RegUser] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [LastUser] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RegDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [LastDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [IsSTDItem] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsOption] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsSet] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsQC] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [SMOutKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [IsBOMReg] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsProcReg] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsProcMat] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [SMLimitTermKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMLimitTermKind] int NULL,
    [IsLotMng] int NULL,
    [IsSerialMng] int NULL,
    [SMAssetGrp] int NULL,
    [PurCustName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [TrustCustName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMVatKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [PriceInVat] int NULL,
    [IsFileCheck] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsImangeCheck] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [StdItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [STDItemSpec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MKCustName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [IsPrice] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [URL] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMPurKind] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [PurKind] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMProperty] int NULL,
    [UMPropertyName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RowIDX] int NULL,
    [ColIDX] int NULL,
    [AddInfoName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_ITEM_INPUT', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_ITEM_INPUT (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSpec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ProcName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [InputQty] decimal(19,5) NULL,
    [WorkOrderSeq] int NULL,
    [WorkOrderNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Price] decimal(19,5) NULL,
    [Amt] decimal(19,5) NULL,
    [InputAcc] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [InputCost] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatAssetName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_ITEM_PROC_MAT', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_ITEM_PROC_MAT (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] int NULL,
    [ItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitSeq] int NULL,
    [UnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ProcRev] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ProcSeq] int NULL,
    [ProcName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyItemSeq] int NULL,
    [AssyItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssySpec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyUnitSeq] int NULL,
    [AssyUnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssyQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatItemSeq] int NULL,
    [MatItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatSpec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatUnitSeq] int NULL,
    [MatUnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [STDUnitSeq] int NULL,
    [STDUnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatQtyNum] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatQtyDen] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [MatQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [STDQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InLossRate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InLossMatQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [OutLossRate] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [OutLossMatQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [LastDateTime] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Memo1] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Memo2] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Memo3] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMDelvType] int NULL,
    [SMDelvTypeName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnit] int NULL,
    [BizUnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UptEmpSeq] int NULL,
    [UptEmpName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UptDate] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [Location] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MasterRemark] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SubItemProcRev] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UserNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSerl] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RegEmpName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RegDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassLName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassMName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatAssetName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatUMItemClassLName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatUMItemClassMName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MatUMItemClassName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [TimeUnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [WorkHour] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_MATERIAL', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_MATERIAL (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] int NULL,
    [ItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMABCName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMStatusName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMInOutKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [DeptName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [EmpName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [STDItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemEngName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassLName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassMName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassSName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RegUserSeq] int NULL,
    [LastUserSeq] int NULL,
    [RegDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [LastDate] nchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [IsSTDItem] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [IsSet] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsQC] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [SMOutKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [IsBOMReg] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsProcMat] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [SMLimitTermKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMLimitTermKind] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [IsLotMng] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsSerialMng] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [SMAssetGrp] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [PurCustName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [TrustCustName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SMVatKindName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [PriceInVat] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsFileCheck] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [IsImageCheck] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [STDItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [STDItemSpec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MKCustName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [IsPrice] nchar(1) COLLATE Korean_Wansung_CI_AS NULL,
    [URL] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMProperty] int NULL,
    [UMPropertyName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_GRP_1] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_GRP_2] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_GRP_4] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_GRP_5] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_GRP_6] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_GRP_7] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_GRP_8] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_GRP_9] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_GRP_10] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_1] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_2] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_3] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_4] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_5] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_6] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_7] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_8] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_9] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_10] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_11] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_12] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_13] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_14] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_15] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_16] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_17] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_18] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_19] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_CMF_20] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [FIRST_FLOW] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [FIRST_FLOW_SEQ_NUM] int NULL,
    [LAST_FLOW] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [LAST_FLOW_SEQ_NUM] int NULL,
    [MFG_DEVISION] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [SUBCONTRACT_FLAG] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [BASE_MAT_ID] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [VENDOR_ID] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [VENDOR_MAT_ID] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [CUSTOMER_ID] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [CUSTOMER_MAT_ID] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [BOM_SET_ID] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [APPLY_START_TIME] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [APPLY_END_TIME] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [APPROVAL_FLAG] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [APPROVAL_USER_ID] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [APPROVAL_TIME] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [RELEASE_FLAG] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [RELEASE_USER_ID] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [RELEASE_TIME] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [DEACTIVE_FLAG] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [DEACTIVE_USER_ID] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [DEACTIVE_TIME] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [MAT_SHORT_DESC] nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [IQC_YN] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [VENDOR] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_PROCESS', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_PROCESS (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [BizUnit] int NULL,
    [ProcSeq] int NULL,
    [ProcName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Remark] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [IsProcQC] int NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_STOCK_DETAIL', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_STOCK_DETAIL (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassSSeq] int NULL,
    [UMItemClassMSeq] int NULL,
    [UMItemClassLSeq] int NULL,
    [UMItemClassSName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItmeClassMName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemClassLName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UMItemEtcClassSeq] int NULL,
    [UMItemEtcClassName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] int NULL,
    [AssetName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [PreQty] decimal(19,5) NULL,
    [PreAmt] decimal(19,5) NULL,
    [ProdQty] decimal(19,5) NULL,
    [ProdAmt] decimal(19,5) NULL,
    [BuyQty] decimal(19,5) NULL,
    [BuyAmt] decimal(19,5) NULL,
    [MvInQty] decimal(19,5) NULL,
    [MvInAmt] decimal(19,5) NULL,
    [EtcInQty] decimal(19,5) NULL,
    [EtcInAmt] decimal(19,5) NULL,
    [ExchangeInQty] decimal(19,5) NULL,
    [ExchangeInAmt] decimal(19,5) NULL,
    [SalesQty] decimal(19,5) NULL,
    [SalesAmt] decimal(19,5) NULL,
    [InputQty] decimal(19,5) NULL,
    [InputAmt] decimal(19,5) NULL,
    [PJTOutQty] decimal(19,5) NULL,
    [PJTOutAmt] decimal(19,5) NULL,
    [MvOutQty] decimal(19,5) NULL,
    [MvOutAmt] decimal(19,5) NULL,
    [EtcOutQty] decimal(19,5) NULL,
    [EtcOutAmt] decimal(19,5) NULL,
    [ExchangeOutQty] decimal(19,5) NULL,
    [ExchangeOutAmt] decimal(19,5) NULL,
    [InQty] decimal(19,5) NULL,
    [OutAmt] decimal(19,5) NULL,
    [InAmt] decimal(19,5) NULL,
    [StockQty] decimal(19,5) NULL,
    [OutQty] decimal(19,5) NULL,
    [StockAmt] decimal(19,5) NULL,
    [StockQty2] decimal(19,5) NULL,
    [StockAmt2] decimal(19,5) NULL,
    [DiffQty] decimal(19,5) NULL,
    [DiffAmt] decimal(19,5) NULL,
    [DivPrice] decimal(19,5) NULL,
    [StkPrice] decimal(19,5) NULL,
    [InputAccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [SalesAccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetGroupName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetAccName] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_WH_STOCK_SUM', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_WH_STOCK_SUM (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [SMAssetGrpName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [WHName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMWHKindName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [AssetName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassLName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassMName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemClassSName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemNo] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Spec] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMStatusName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [PrevQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [InQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [OutQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [StockQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [ItemSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [UnitSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [WHSeq] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SMWHKind] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Location] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [SafetyQty] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [CostWHName] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [IsLot] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_IF_WIP_SUBUL', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_IF_WIP_SUBUL (
    [SITE] nvarchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (N'VN'),
    [SEL_CODE] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [LOAD_DTTM] datetime NOT NULL DEFAULT (getdate()),
    [REQUEST_ID] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [factory] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [mat_id] varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [mat_grp_1] varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [work_date] varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
    [boh_a_wip_before_pfl_50] int NULL,
    [boh_a_wip_after_pfl_90] int NULL,
    [boh_a_fgs_before_pfl_50] int NULL,
    [boh_a_fgs_after_pfl_90] int NULL,
    [boh_a_before_pfl_50] int NULL,
    [boh_a_after_pfl_90] int NULL,
    [boh_b_wip_before_pfl_50] int NULL,
    [boh_b_wip_after_pfl_90] int NULL,
    [boh_b_fgs_before_pfl_50] int NULL,
    [boh_b_fgs_after_pfl_90] int NULL,
    [boh_b_before_pfl_50] int NULL,
    [boh_b_after_pfl_90] int NULL,
    [t_boh_before_pfl_50] int NULL,
    [t_boh_after_pfl_90] int NULL,
    [input_usc_cutting_qty] int NULL,
    [change_code_qty] int NULL,
    [input_re_sorting_qty] int NULL,
    [input_rework_qty] int NULL,
    [wip_etc_input] int NULL,
    [total_input_to_line] int NULL,
    [total_input] int NULL,
    [normal_last_month] int NULL,
    [normal_this_month] int NULL,
    [wh_rt_sorting] int NULL,
    [wh_rt_pfrw] int NULL,
    [wh_rt_plrw] int NULL,
    [backship_sorting] int NULL,
    [backship_pfrw] int NULL,
    [backship_plrw] int NULL,
    [total_out_a_level] int NULL,
    [output_code_change_50] int NULL,
    [output_code_change_90] int NULL,
    [output_other_50] int NULL,
    [output_other_90] int NULL,
    [b_level_ship_paid_50] int NULL,
    [b_level_ship_paid_90] int NULL,
    [b_level_ship_paid] int NULL,
    [b_level_ship_free_50] int NULL,
    [b_level_ship_free_90] int NULL,
    [b_level_ship_free] int NULL,
    [b_level_ship_50] int NULL,
    [b_level_ship_90] int NULL,
    [total_out_b_level] int NULL,
    [total_output] int NULL,
    [scrap_before_pfl] int NULL,
    [scrap_after_pfl] int NULL,
    [scrap_total_qty] int NULL,
    [eoh_line_wip_pfl_50] int NULL,
    [eoh_line_wip_pfl_90] int NULL,
    [eoh_line_fgs_pfl_50] int NULL,
    [eoh_line_fgs_pfl_90] int NULL,
    [eoh_b_wip_pfl_50] int NULL,
    [eoh_b_wip_pfl_90] int NULL,
    [eoh_b_fgs_pfl_50] int NULL,
    [eoh_b_fgs_pfl_90] int NULL,
    [t_eoh_wip_pfl_50] int NULL,
    [t_eoh_wip_pfl_90] int NULL,
    [t_eoh_b_pfl_50] int NULL,
    [t_eoh_b_pfl_90] int NULL,
    [t_eoh_mes_pfl_50] int NULL,
    [t_eoh_mes_pfl_90] int NULL,
    [RAW_JSON] nvarchar(max) COLLATE Korean_Wansung_CI_AS NULL
);
GO

