-- ⚠️운영(도우제조원가시스템) 배포용. dev(DWCMSTEST) 라이브 정의에서 추출(2026-08-28).
-- 검토 후 운영에서 실행. 멱등(존재시 스킵/ALTER).

-- xform 기록대상 중 운영 부재 5종.
-- ★DOI_VN_STCO/stock_resc/prod_resc 는 VN _NEW 결산 파이프라인 테이블 —
--   전체 결산 배포의 일부. 여기선 인터페이스 xform 오류 방지용 구조만 생성(PK/인덱스/파이프라인 별도 확인).

IF OBJECT_ID(N'dbo.DOI_HQ_STOCK_DETAIL', N'U') IS NULL
CREATE TABLE dbo.DOI_HQ_STOCK_DETAIL (
    [자산처리계정] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [품목자산분류] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [재고자산종류] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [매출원가계정] numeric(28,8) NULL,
    [대분류] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [중분류] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [소분류] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [품목기타분류] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [품명] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [품번] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [규격] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [단위] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [기초수량] numeric(28,8) NULL,
    [기초금액] numeric(28,8) NULL,
    [입고수량] numeric(28,8) NULL,
    [입고금액] numeric(28,8) NULL,
    [출고수량] numeric(28,8) NULL,
    [출고금액] numeric(28,8) NULL,
    [재고수량A] numeric(28,8) NULL,
    [결산후재고수량B] numeric(28,8) NULL,
    [차이수량A_B] numeric(28,8) NULL,
    [재고금액C] numeric(28,8) NULL,
    [결산후재고금액D] numeric(28,8) NULL,
    [차이금액C_D] numeric(28,8) NULL,
    [최종결산월재고단가] numeric(28,8) NULL,
    [생산수량] numeric(28,8) NULL,
    [생산금액] numeric(28,8) NULL,
    [구매수량] numeric(28,8) NULL,
    [구매금액] numeric(28,8) NULL,
    [적송입고수량] numeric(28,8) NULL,
    [적송입고금액] numeric(28,8) NULL,
    [기타입고수량] numeric(28,8) NULL,
    [기타입고금액] numeric(28,8) NULL,
    [판매수량] numeric(28,8) NULL,
    [판매원가] numeric(28,8) NULL,
    [투입수량] numeric(28,8) NULL,
    [투입금액] numeric(28,8) NULL,
    [적송출고수량] numeric(28,8) NULL,
    [적송출고금액] numeric(28,8) NULL,
    [기타출고수량] numeric(28,8) NULL,
    [기타출고금액] numeric(28,8) NULL,
    [yyyymm] varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [edit_user] nvarchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [edit_date] datetime NOT NULL
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_STCO', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_STCO (
    [yyyymm] varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [sel_code] varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT ('ACTUAL'),
    [도우코드] nvarchar(30) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [division] varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (''),
    [EXPEN_SEL] varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT ('*'),
    [구분] nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [MODEL] varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [expen_sel명] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ACCT_NAME] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [ITEM_NAME] nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
    [UNIT_COST] numeric(24,12) NULL,
    [BOH_QTY] numeric(18,2) NULL,
    [BOH_AMT] numeric(18,2) NULL,
    [IN_NORMAL_LAST_QTY] numeric(18,2) NULL,
    [IN_NORMAL_LAST_AMT] numeric(18,2) NULL,
    [IN_NORMAL_THIS_QTY] numeric(18,2) NULL,
    [IN_NORMAL_THIS_AMT] numeric(18,2) NULL,
    [IN_RW_BACKSHIP_SORT_QTY] numeric(18,2) NULL,
    [IN_RW_BACKSHIP_SORT_AMT] numeric(18,2) NULL,
    [IN_RW_BACKSHIP_PFRW_QTY] numeric(18,2) NULL,
    [IN_RW_BACKSHIP_PFRW_AMT] numeric(18,2) NULL,
    [IN_RW_BACKSHIP_PLRW_QTY] numeric(18,2) NULL,
    [IN_RW_BACKSHIP_PLRW_AMT] numeric(18,2) NULL,
    [IN_RW_WHRET_SORT_QTY] numeric(18,2) NULL,
    [IN_RW_WHRET_SORT_AMT] numeric(18,2) NULL,
    [IN_RW_WHRET_PFRW_QTY] numeric(18,2) NULL,
    [IN_RW_WHRET_PFRW_AMT] numeric(18,2) NULL,
    [IN_RW_WHRET_PLRW_QTY] numeric(18,2) NULL,
    [IN_RW_WHRET_PLRW_AMT] numeric(18,2) NULL,
    [T_INPUT_QTY] numeric(18,2) NULL,
    [T_INPUT_AMT] numeric(18,2) NULL,
    [ETCIN_RMA_QTY] numeric(18,2) NULL,
    [ETCIN_RMA_AMT] numeric(18,2) NULL,
    [ETCIN_SEMI_PAID_QTY] numeric(18,2) NULL,
    [ETCIN_SEMI_PAID_AMT] numeric(18,2) NULL,
    [ETCIN_SEMI_FREE_QTY] numeric(18,2) NULL,
    [ETCIN_SEMI_FREE_AMT] numeric(18,2) NULL,
    [ETCIN_ETC_QTY] numeric(18,2) NULL,
    [ETCIN_ETC_AMT] numeric(18,2) NULL,
    [ETCIN_TOTAL_QTY] numeric(18,2) NULL,
    [ETCIN_TOTAL_AMT] numeric(18,2) NULL,
    [OUT_SHIP_A_PAID_QTY] numeric(18,2) NULL,
    [OUT_SHIP_A_PAID_AMT] numeric(18,2) NULL,
    [OUT_SHIP_A_FREE_QTY] numeric(18,2) NULL,
    [OUT_SHIP_A_FREE_AMT] numeric(18,2) NULL,
    [OUT_SHIP_B_QTY] numeric(18,2) NULL,
    [OUT_SHIP_B_AMT] numeric(18,2) NULL,
    [T_OUTPUT_QTY] numeric(18,2) NULL,
    [T_OUTPUT_AMT] numeric(18,2) NULL,
    [ETCOUT_RESORT_QTY] numeric(18,2) NULL,
    [ETCOUT_RESORT_AMT] numeric(18,2) NULL,
    [ETCOUT_REWORK_QTY] numeric(18,2) NULL,
    [ETCOUT_REWORK_AMT] numeric(18,2) NULL,
    [ETCOUT_FREESALE_QTY] numeric(18,2) NULL,
    [ETCOUT_FREESALE_AMT] numeric(18,2) NULL,
    [ETCOUT_ETC_QTY] numeric(18,2) NULL,
    [ETCOUT_ETC_AMT] numeric(18,2) NULL,
    [ETCOUT_TOTAL_QTY] numeric(18,2) NULL,
    [ETCOUT_TOTAL_AMT] numeric(18,2) NULL,
    [LOSS_QTY] numeric(18,2) NULL,
    [LOSS_AMT] numeric(18,2) NULL,
    [EOH_WH0006_QTY] numeric(18,2) NULL,
    [EOH_WH0006_AMT] numeric(18,2) NULL,
    [VERIFY] numeric(18,2) NULL,
    [EDIT_USER] varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [EDIT_DT] datetime NULL DEFAULT (getdate()),
    PRIMARY KEY ([yyyymm], [sel_code], [도우코드], [division], [EXPEN_SEL])
);
GO

IF OBJECT_ID(N'dbo.doi_vn_stock_resc', N'U') IS NULL
CREATE TABLE dbo.doi_vn_stock_resc (
    [yyyymm] varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [sel_code] varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT ('ACTUAL'),
    [도우코드] nvarchar(30) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [division] varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (''),
    [BOH] numeric(18,2) NULL,
    [IN_NORMAL_LAST] numeric(18,2) NULL,
    [IN_NORMAL_THIS] numeric(18,2) NULL,
    [IN_RW_BACKSHIP_SORT] numeric(18,2) NULL,
    [IN_RW_BACKSHIP_PFRW] numeric(18,2) NULL,
    [IN_RW_BACKSHIP_PLRW] numeric(18,2) NULL,
    [IN_RW_WHRET_SORT] numeric(18,2) NULL,
    [IN_RW_WHRET_PFRW] numeric(18,2) NULL,
    [IN_RW_WHRET_PLRW] numeric(18,2) NULL,
    [T_INPUT] numeric(18,2) NULL,
    [ETCIN_RMA] numeric(18,2) NULL,
    [ETCIN_SEMI_PAID] numeric(18,2) NULL,
    [ETCIN_SEMI_FREE] numeric(18,2) NULL,
    [ETCIN_ETC] numeric(18,2) NULL,
    [ETCIN_TOTAL] numeric(18,2) NULL,
    [OUT_SHIP_A_PAID] numeric(18,2) NULL,
    [OUT_SHIP_A_FREE] numeric(18,2) NULL,
    [OUT_SHIP_B] numeric(18,2) NULL,
    [T_OUTPUT] numeric(18,2) NULL,
    [ETCOUT_RESORT] numeric(18,2) NULL,
    [ETCOUT_REWORK] numeric(18,2) NULL,
    [ETCOUT_FREESALE] numeric(18,2) NULL,
    [ETCOUT_ETC] numeric(18,2) NULL,
    [ETCOUT_TOTAL] numeric(18,2) NULL,
    [LOSS] numeric(18,2) NULL,
    [EOH_WH0006] numeric(18,2) NULL,
    [VERIFY] numeric(18,2) NULL,
    [EDIT_USER] varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [EDIT_DT] datetime NULL DEFAULT (getdate()),
    PRIMARY KEY ([yyyymm], [sel_code], [도우코드], [division])
);
GO

IF OBJECT_ID(N'dbo.doi_vn_prod_resc', N'U') IS NULL
CREATE TABLE dbo.doi_vn_prod_resc (
    [yyyymm] varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [sel_code] varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT ('ACTUAL'),
    [도우코드] nvarchar(30) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [division] varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT (''),
    [BOH_LINE_WIP_전] numeric(18,2) NULL,
    [BOH_LINE_WIP_후] numeric(18,2) NULL,
    [BOH_LINE_FGS_전] numeric(18,2) NULL,
    [BOH_LINE_FGS_후] numeric(18,2) NULL,
    [BOH_A_SUB_전] numeric(18,2) NULL,
    [BOH_A_SUB_후] numeric(18,2) NULL,
    [BOH_B_WIP_전] numeric(18,2) NULL,
    [BOH_B_WIP_후] numeric(18,2) NULL,
    [BOH_B_FGS_전] numeric(18,2) NULL,
    [BOH_B_FGS_후] numeric(18,2) NULL,
    [BOH_B_SUB_전] numeric(18,2) NULL,
    [BOH_B_SUB_후] numeric(18,2) NULL,
    [T_BOH_전] numeric(18,2) NULL,
    [T_BOH_후] numeric(18,2) NULL,
    [USC_INPUT] numeric(18,2) NULL,
    [ETCIN_CODE] numeric(18,2) NULL,
    [ETCIN_RESORT] numeric(18,2) NULL,
    [ETCIN_REWORK] numeric(18,2) NULL,
    [ETCIN_SEMI] numeric(18,2) NULL,
    [ETCIN_ETC] numeric(18,2) NULL,
    [ETCIN_TOTAL] numeric(18,2) NULL,
    [OUTPUT_A] numeric(18,2) NULL,
    [ETCOUT_CODE_전] numeric(18,2) NULL,
    [ETCOUT_CODE_후] numeric(18,2) NULL,
    [ETCOUT_SEMI_PAID_전] numeric(18,2) NULL,
    [ETCOUT_SEMI_PAID_후] numeric(18,2) NULL,
    [ETCOUT_SEMI_FREE_전] numeric(18,2) NULL,
    [ETCOUT_SEMI_FREE_후] numeric(18,2) NULL,
    [ETCOUT_ETC_전] numeric(18,2) NULL,
    [ETCOUT_ETC_후] numeric(18,2) NULL,
    [ETCOUT_TOTAL_전] numeric(18,2) NULL,
    [ETCOUT_TOTAL_후] numeric(18,2) NULL,
    [LOSS_전] numeric(18,2) NULL,
    [LOSS_후] numeric(18,2) NULL,
    [EOH_LINE_WIP_전] numeric(18,2) NULL,
    [EOH_LINE_WIP_후] numeric(18,2) NULL,
    [EOH_LINE_FGS_전] numeric(18,2) NULL,
    [EOH_LINE_FGS_후] numeric(18,2) NULL,
    [EOH_B_WIP_전] numeric(18,2) NULL,
    [EOH_B_WIP_후] numeric(18,2) NULL,
    [EOH_B_FGS_전] numeric(18,2) NULL,
    [EOH_B_FGS_후] numeric(18,2) NULL,
    [T_EOH_WIP_전] numeric(18,2) NULL,
    [T_EOH_WIP_후] numeric(18,2) NULL,
    [T_EOH_FGS_전] numeric(18,2) NULL,
    [T_EOH_FGS_후] numeric(18,2) NULL,
    [TOTAL_EOH_전] numeric(18,2) NULL,
    [TOTAL_EOH_후] numeric(18,2) NULL,
    [EDIT_USER] varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [EDIT_DT] datetime NULL DEFAULT (getdate()),
    PRIMARY KEY ([yyyymm], [sel_code], [도우코드], [division])
);
GO

IF OBJECT_ID(N'dbo.DOI_VN_EXP_CLAIM', N'U') IS NULL
CREATE TABLE dbo.DOI_VN_EXP_CLAIM (
    [yyyymm] varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
    [sel_code] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [site] varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
    [사업단위] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Claim번호] varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
    [ClaimDate] varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
    [반품종류] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [반품구분] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [담당자] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [부서] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Buyer] varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
    [Agent] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [반품진행] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [재수출진행] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [통화] varchar(5) COLLATE Korean_Wansung_CI_AS NULL,
    [환율] numeric(18,5) NULL,
    [품명] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [품번] varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
    [규격] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [판매단위] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [기준단위] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [기준단위수량] numeric(18,3) NULL,
    [정가] numeric(18,5) NULL,
    [판매기준가] numeric(18,5) NULL,
    [판매단가] numeric(18,5) NULL,
    [수량] numeric(18,3) NULL,
    [판매금액] numeric(18,2) NULL,
    [원화판매금액] numeric(18,2) NULL,
    [창고] nvarchar(200) COLLATE Korean_Wansung_CI_AS NULL,
    [Remarks] nvarchar(1000) COLLATE Korean_Wansung_CI_AS NULL,
    [edit_user] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
    [edit_date] datetime NULL
);
GO

