/**
 * Tab090002 - 월별, 기간별(누적) 조회
 * RealGrid Definition
 */

const tab090002GridField = {
  fields: [
    { fieldName: '구분', dataType: 'text' },
    { fieldName: '코드', dataType: 'text' },
    { fieldName: 'inch', dataType: 'text' },
    { fieldName: 'site', dataType: 'text' },
    { fieldName: '계획', dataType: 'number' },
    { fieldName: '실적', dataType: 'number' },
    { fieldName: '달성률', dataType: 'number' },
    { fieldName: 'boh', dataType: 'number' },
    { fieldName: 'inMonth', dataType: 'number' },
    { fieldName: 'outMonth', dataType: 'number' },
    { fieldName: 'lossMonth', dataType: 'number' },
    { fieldName: 'eoh', dataType: 'number' },
    { fieldName: '불량률', dataType: 'number' },
    { fieldName: '수율', dataType: 'number' },
  ],
  columns: [
    {
      name: '구분',
      fieldName: '구분',
      type: 'data',
      width: '120',
      header: { text: '구분' },
      styleName: 'left-column',
    },
    {
      name: '코드',
      fieldName: '코드',
      type: 'data',
      width: '100',
      header: { text: '코드' },
      styleName: 'center-column',
    },
    {
      name: 'inch',
      fieldName: 'inch',
      type: 'data',
      width: '80',
      header: { text: 'Inch' },
      styleName: 'center-column',
    },
    {
      name: 'site',
      fieldName: 'site',
      type: 'data',
      width: '80',
      header: { text: 'SITE' },
      styleName: 'center-column',
    },
    {
      name: '계획',
      fieldName: '계획',
      type: 'data',
      width: '100',
      header: { text: '계획(누적)' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: '실적',
      fieldName: '실적',
      type: 'data',
      width: '100',
      header: { text: '실적(누적)' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: '달성률',
      fieldName: '달성률',
      type: 'data',
      width: '100',
      header: { text: '달성률' },
      styleName: 'right-column',
      numberFormat: '#,##0.00%',
    },
    {
      name: 'boh',
      fieldName: 'boh',
      type: 'data',
      width: '100',
      header: { text: 'BOH' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'inMonth',
      fieldName: 'inMonth',
      type: 'data',
      width: '100',
      header: { text: 'IN(누적)' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'outMonth',
      fieldName: 'outMonth',
      type: 'data',
      width: '100',
      header: { text: 'OUT(누적)' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'lossMonth',
      fieldName: 'lossMonth',
      type: 'data',
      width: '100',
      header: { text: 'LOSS(누적)' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'eoh',
      fieldName: 'eoh',
      type: 'data',
      width: '100',
      header: { text: 'EOH' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: '불량률',
      fieldName: '불량률',
      type: 'data',
      width: '100',
      header: { text: '불량률' },
      styleName: 'right-column',
      numberFormat: '#,##0.00%',
    },
    {
      name: '수율',
      fieldName: '수율',
      type: 'data',
      width: '100',
      header: { text: '수율' },
      styleName: 'right-column',
      numberFormat: '#,##0.00%',
    },
  ],
  options: {
    edit: { editable: false },
    display: { fitStyle: 'evenFill' },
    footer: { visible: true },
  },
};

export default tab090002GridField;
