/**
 * Tab090003 - 년간 전체 실적 집계
 * RealGrid Definition - 12개월 컬럼 표시
 */

const tab090003GridField = {
  fields: [
    { fieldName: '구분', dataType: 'text' },
    { fieldName: '코드', dataType: 'text' },
    { fieldName: 'inch', dataType: 'text' },
    { fieldName: 'site', dataType: 'text' },
    { fieldName: 'm01', dataType: 'number' },
    { fieldName: 'm02', dataType: 'number' },
    { fieldName: 'm03', dataType: 'number' },
    { fieldName: 'm04', dataType: 'number' },
    { fieldName: 'm05', dataType: 'number' },
    { fieldName: 'm06', dataType: 'number' },
    { fieldName: 'm07', dataType: 'number' },
    { fieldName: 'm08', dataType: 'number' },
    { fieldName: 'm09', dataType: 'number' },
    { fieldName: 'm10', dataType: 'number' },
    { fieldName: 'm11', dataType: 'number' },
    { fieldName: 'm12', dataType: 'number' },
    { fieldName: 'total', dataType: 'number' },
  ],
  columns: [
    {
      name: '구분',
      fieldName: '구분',
      type: 'data',
      width: '120',
      header: { text: '구분' },
      styleName: 'left-column',
    },
    {
      name: '코드',
      fieldName: '코드',
      type: 'data',
      width: '100',
      header: { text: '코드' },
      styleName: 'center-column',
    },
    {
      name: 'inch',
      fieldName: 'inch',
      type: 'data',
      width: '80',
      header: { text: 'Inch' },
      styleName: 'center-column',
    },
    {
      name: 'site',
      fieldName: 'site',
      type: 'data',
      width: '80',
      header: { text: 'SITE' },
      styleName: 'center-column',
    },
    {
      name: 'm01',
      fieldName: 'm01',
      type: 'data',
      width: '90',
      header: { text: '1월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm02',
      fieldName: 'm02',
      type: 'data',
      width: '90',
      header: { text: '2월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm03',
      fieldName: 'm03',
      type: 'data',
      width: '90',
      header: { text: '3월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm04',
      fieldName: 'm04',
      type: 'data',
      width: '90',
      header: { text: '4월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm05',
      fieldName: 'm05',
      type: 'data',
      width: '90',
      header: { text: '5월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm06',
      fieldName: 'm06',
      type: 'data',
      width: '90',
      header: { text: '6월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm07',
      fieldName: 'm07',
      type: 'data',
      width: '90',
      header: { text: '7월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm08',
      fieldName: 'm08',
      type: 'data',
      width: '90',
      header: { text: '8월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm09',
      fieldName: 'm09',
      type: 'data',
      width: '90',
      header: { text: '9월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm10',
      fieldName: 'm10',
      type: 'data',
      width: '90',
      header: { text: '10월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm11',
      fieldName: 'm11',
      type: 'data',
      width: '90',
      header: { text: '11월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'm12',
      fieldName: 'm12',
      type: 'data',
      width: '90',
      header: { text: '12월' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
    {
      name: 'total',
      fieldName: 'total',
      type: 'data',
      width: '120',
      header: { text: '합계' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: {
        expression: 'sum',
        numberFormat: '#,##0',
      },
    },
  ],
  options: {
    edit: { editable: false },
    display: { fitStyle: 'evenFill' },
    footer: { visible: true },
  },
};

export default tab090003GridField;
