/**
 * TAB090014 - 재공품 공정 수불
 * RealGrid Definition
 */

const tab090014GridField = {
  fields: [
    { fieldName: 'model', dataType: 'text' },
    { fieldName: 'process', dataType: 'text' },
    { fieldName: 'boh', dataType: 'number' },
    { fieldName: 'inQty', dataType: 'number' },
    { fieldName: 'outQty', dataType: 'number' },
    { fieldName: 'lossQty', dataType: 'number' },
    { fieldName: 'etcInCode', dataType: 'number' },
    { fieldName: 'etcInResort', dataType: 'number' },
    { fieldName: 'etcInRework', dataType: 'number' },
    { fieldName: 'etcInSemi', dataType: 'number' },
    { fieldName: 'etcInEtc', dataType: 'number' },
    { fieldName: 'otherAccInTotal', dataType: 'number' },
    { fieldName: 'etcOutCode', dataType: 'number' },
    { fieldName: 'etcOutSemiPaid', dataType: 'number' },
    { fieldName: 'etcOutSemiFree', dataType: 'number' },
    { fieldName: 'etcOutEtc', dataType: 'number' },
    { fieldName: 'otherAccOutTotal', dataType: 'number' },
    { fieldName: 'eoh', dataType: 'number' },
    { fieldName: 'wipValRate', dataType: 'number' },
  ],
  columns: [
    {
      name: 'model',
      fieldName: 'model',
      type: 'data',
      width: '110',
      header: { text: '모델' },
      styleName: 'left-column',
      autoFilter: true,
    },
    {
      name: 'process',
      fieldName: 'process',
      type: 'data',
      width: '100',
      header: { text: '공정' },
      styleName: 'center-column',
      autoFilter: true,
    },
    {
      name: 'boh',
      fieldName: 'boh',
      type: 'data',
      width: '90',
      header: { text: '기초' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'inQty',
      fieldName: 'inQty',
      type: 'data',
      width: '90',
      header: { text: '입고' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'outQty',
      fieldName: 'outQty',
      type: 'data',
      width: '90',
      header: { text: '출고' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'lossQty',
      fieldName: 'lossQty',
      type: 'data',
      width: '90',
      header: { text: 'LOSS' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'etcInCode',
      fieldName: 'etcInCode',
      type: 'data',
      width: '110',
      header: { text: '기타입고\n(Code 변경)' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'etcInResort',
      fieldName: 'etcInResort',
      type: 'data',
      width: '130',
      header: { text: '기타입고\n(Re-Sorting, Rework, SI)' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'etcInRework',
      fieldName: 'etcInRework',
      type: 'data',
      width: '130',
      header: { text: '기타입고\n(Re-work 입고)-SI검사' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'etcInSemi',
      fieldName: 'etcInSemi',
      type: 'data',
      width: '110',
      header: { text: '기타입고\n(반제품 입고)' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'etcInEtc',
      fieldName: 'etcInEtc',
      type: 'data',
      width: '90',
      header: { text: '기타입고\n(기타)' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'otherAccInTotal',
      fieldName: 'otherAccInTotal',
      type: 'data',
      width: '100',
      header: { text: '타계정입고 계' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'etcOutCode',
      fieldName: 'etcOutCode',
      type: 'data',
      width: '110',
      header: { text: '기타출고\n(Code 변경)' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'etcOutSemiPaid',
      fieldName: 'etcOutSemiPaid',
      type: 'data',
      width: '90',
      header: { text: '유상' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'etcOutSemiFree',
      fieldName: 'etcOutSemiFree',
      type: 'data',
      width: '90',
      header: { text: '무상' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'etcOutEtc',
      fieldName: 'etcOutEtc',
      type: 'data',
      width: '90',
      header: { text: '기타' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'otherAccOutTotal',
      fieldName: 'otherAccOutTotal',
      type: 'data',
      width: '100',
      header: { text: '타계정출고 계' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'eoh',
      fieldName: 'eoh',
      type: 'data',
      width: '90',
      header: { text: '재고' },
      styleName: 'right-column',
      numberFormat: '#,##0',
      footer: { expression: 'sum', numberFormat: '#,##0' },
    },
    {
      name: 'wipValRate',
      fieldName: 'wipValRate',
      type: 'data',
      width: '100',
      header: { text: '재공평가비율' },
      styleName: 'right-column',
      numberFormat: '#,##0.0%',
    },
  ],
  layout: [
    'model',
    'process',
    'boh',
    'inQty',
    'outQty',
    'lossQty',
    {
      name: 'otherAccInGroup',
      direction: 'horizontal',
      items: [
        'etcInCode',
        'etcInResort',
        'etcInRework',
        'etcInSemi',
        'etcInEtc',
        'otherAccInTotal',
      ],
      header: { text: '타계정입고' },
    },
    {
      name: 'otherAccOutGroup',
      direction: 'horizontal',
      items: [
        'etcOutCode',
        {
          name: 'etcOutSemiGroup',
          direction: 'horizontal',
          items: ['etcOutSemiPaid', 'etcOutSemiFree'],
          header: { text: '기타출고(반제품 출고)' },
        },
        'etcOutEtc',
        'otherAccOutTotal',
      ],
      header: { text: '타계정출고' },
    },
    'eoh',
    'wipValRate',
  ],
  options: {
    edit: { editable: false },
    display: { fitStyle: 'evenFill' },
    footer: { visible: true },
  },
};

export default tab090014GridField;
