/* [VN 260801] doi_vn_cost = doi_vn_prod_resc 리프 포지션 미러(QTY+AMT) + expen_sel(원가항목)
   신규포맷 재공평가 출력 (소계/토탈 컬럼은 생략, 자식합으로 도출). 그레인=(도우코드,division,EXPEN_SEL) */
IF OBJECT_ID('doi_vn_cost') IS NOT NULL DROP TABLE doi_vn_cost;
CREATE TABLE doi_vn_cost (
  YYYYMM varchar(6) NOT NULL, SEL_CODE varchar(10) NOT NULL DEFAULT 'ACTUAL', SITE varchar(4) NOT NULL DEFAULT 'VN',
  도우코드 nvarchar(30) NOT NULL, division varchar(10) NOT NULL DEFAULT '',
  구분 nvarchar(10) NULL, MODEL varchar(50) NULL,
  EXPEN_SEL varchar(10) NOT NULL DEFAULT '*', expen_sel명 nvarchar(100) NULL, ACCT_NAME nvarchar(100) NULL, ITEM_NAME nvarchar(100) NULL,
  UNIT_COST numeric(24,12) NULL, ADJ_YN varchar(1) NULL DEFAULT 'N',
  [BOH_LINE_WIP_전_QTY] numeric(18,2) NULL, [BOH_LINE_WIP_전_AMT] numeric(18,2) NULL,
  [BOH_LINE_WIP_후_QTY] numeric(18,2) NULL, [BOH_LINE_WIP_후_AMT] numeric(18,2) NULL,
  [BOH_LINE_FGS_전_QTY] numeric(18,2) NULL, [BOH_LINE_FGS_전_AMT] numeric(18,2) NULL,
  [BOH_LINE_FGS_후_QTY] numeric(18,2) NULL, [BOH_LINE_FGS_후_AMT] numeric(18,2) NULL,
  [BOH_B_WIP_전_QTY] numeric(18,2) NULL, [BOH_B_WIP_전_AMT] numeric(18,2) NULL,
  [BOH_B_WIP_후_QTY] numeric(18,2) NULL, [BOH_B_WIP_후_AMT] numeric(18,2) NULL,
  [BOH_B_FGS_전_QTY] numeric(18,2) NULL, [BOH_B_FGS_전_AMT] numeric(18,2) NULL,
  [BOH_B_FGS_후_QTY] numeric(18,2) NULL, [BOH_B_FGS_후_AMT] numeric(18,2) NULL,
  [USC_INPUT_QTY] numeric(18,2) NULL, [USC_INPUT_AMT] numeric(18,2) NULL,
  [ETCIN_CODE_QTY] numeric(18,2) NULL, [ETCIN_CODE_AMT] numeric(18,2) NULL,
  [ETCIN_RESORT_QTY] numeric(18,2) NULL, [ETCIN_RESORT_AMT] numeric(18,2) NULL,
  [ETCIN_REWORK_QTY] numeric(18,2) NULL, [ETCIN_REWORK_AMT] numeric(18,2) NULL,
  [ETCIN_SEMI_QTY] numeric(18,2) NULL, [ETCIN_SEMI_AMT] numeric(18,2) NULL,
  [ETCIN_ETC_QTY] numeric(18,2) NULL, [ETCIN_ETC_AMT] numeric(18,2) NULL,
  [OUTPUT_A_QTY] numeric(18,2) NULL, [OUTPUT_A_AMT] numeric(18,2) NULL,
  [ETCOUT_CODE_전_QTY] numeric(18,2) NULL, [ETCOUT_CODE_전_AMT] numeric(18,2) NULL,
  [ETCOUT_CODE_후_QTY] numeric(18,2) NULL, [ETCOUT_CODE_후_AMT] numeric(18,2) NULL,
  [ETCOUT_SEMI_PAID_전_QTY] numeric(18,2) NULL, [ETCOUT_SEMI_PAID_전_AMT] numeric(18,2) NULL,
  [ETCOUT_SEMI_PAID_후_QTY] numeric(18,2) NULL, [ETCOUT_SEMI_PAID_후_AMT] numeric(18,2) NULL,
  [ETCOUT_SEMI_FREE_전_QTY] numeric(18,2) NULL, [ETCOUT_SEMI_FREE_전_AMT] numeric(18,2) NULL,
  [ETCOUT_SEMI_FREE_후_QTY] numeric(18,2) NULL, [ETCOUT_SEMI_FREE_후_AMT] numeric(18,2) NULL,
  [ETCOUT_ETC_전_QTY] numeric(18,2) NULL, [ETCOUT_ETC_전_AMT] numeric(18,2) NULL,
  [ETCOUT_ETC_후_QTY] numeric(18,2) NULL, [ETCOUT_ETC_후_AMT] numeric(18,2) NULL,
  [LOSS_전_QTY] numeric(18,2) NULL, [LOSS_전_AMT] numeric(18,2) NULL,
  [LOSS_후_QTY] numeric(18,2) NULL, [LOSS_후_AMT] numeric(18,2) NULL,
  [EOH_LINE_WIP_전_QTY] numeric(18,2) NULL, [EOH_LINE_WIP_전_AMT] numeric(18,2) NULL,
  [EOH_LINE_WIP_후_QTY] numeric(18,2) NULL, [EOH_LINE_WIP_후_AMT] numeric(18,2) NULL,
  [EOH_LINE_FGS_전_QTY] numeric(18,2) NULL, [EOH_LINE_FGS_전_AMT] numeric(18,2) NULL,
  [EOH_LINE_FGS_후_QTY] numeric(18,2) NULL, [EOH_LINE_FGS_후_AMT] numeric(18,2) NULL,
  [EOH_B_WIP_전_QTY] numeric(18,2) NULL, [EOH_B_WIP_전_AMT] numeric(18,2) NULL,
  [EOH_B_WIP_후_QTY] numeric(18,2) NULL, [EOH_B_WIP_후_AMT] numeric(18,2) NULL,
  [EOH_B_FGS_전_QTY] numeric(18,2) NULL, [EOH_B_FGS_전_AMT] numeric(18,2) NULL,
  [EOH_B_FGS_후_QTY] numeric(18,2) NULL, [EOH_B_FGS_후_AMT] numeric(18,2) NULL,
  EDIT_USER varchar(50) NULL, EDIT_DT datetime NULL DEFAULT getdate(),
  CONSTRAINT PK_doi_vn_cost PRIMARY KEY (YYYYMM, SEL_CODE, 도우코드, division, EXPEN_SEL)
);

/* [VN 260801 V11-3] doi_vn_stco = 제품 매출원가(신규포맷, OUTPUT 3분할 SHIP_A유상/무상/B) + expen_sel. 그레인=(도우코드,division,EXPEN_SEL) */
CREATE TABLE doi_vn_stco (
  yyyymm varchar(6) NOT NULL, sel_code varchar(10) NOT NULL DEFAULT 'ACTUAL',
  도우코드 nvarchar(30) NOT NULL, division varchar(10) NOT NULL DEFAULT '',
  EXPEN_SEL varchar(10) NOT NULL DEFAULT '*', 구분 nvarchar(10) NULL, MODEL varchar(50) NULL,
  expen_sel명 nvarchar(100) NULL, ACCT_NAME nvarchar(100) NULL, ITEM_NAME nvarchar(100) NULL, UNIT_COST numeric(24,12) NULL,
  [BOH_QTY] numeric(18,2) NULL, [BOH_AMT] numeric(18,2) NULL,
  [IN_NORMAL_LAST_QTY] numeric(18,2) NULL, [IN_NORMAL_LAST_AMT] numeric(18,2) NULL,
  [IN_NORMAL_THIS_QTY] numeric(18,2) NULL, [IN_NORMAL_THIS_AMT] numeric(18,2) NULL,
  [IN_RW_BACKSHIP_SORT_QTY] numeric(18,2) NULL, [IN_RW_BACKSHIP_SORT_AMT] numeric(18,2) NULL,
  [IN_RW_BACKSHIP_PFRW_QTY] numeric(18,2) NULL, [IN_RW_BACKSHIP_PFRW_AMT] numeric(18,2) NULL,
  [IN_RW_BACKSHIP_PLRW_QTY] numeric(18,2) NULL, [IN_RW_BACKSHIP_PLRW_AMT] numeric(18,2) NULL,
  [IN_RW_WHRET_SORT_QTY] numeric(18,2) NULL, [IN_RW_WHRET_SORT_AMT] numeric(18,2) NULL,
  [IN_RW_WHRET_PFRW_QTY] numeric(18,2) NULL, [IN_RW_WHRET_PFRW_AMT] numeric(18,2) NULL,
  [IN_RW_WHRET_PLRW_QTY] numeric(18,2) NULL, [IN_RW_WHRET_PLRW_AMT] numeric(18,2) NULL,
  [T_INPUT_QTY] numeric(18,2) NULL, [T_INPUT_AMT] numeric(18,2) NULL,
  [ETCIN_RMA_QTY] numeric(18,2) NULL, [ETCIN_RMA_AMT] numeric(18,2) NULL,
  [ETCIN_SEMI_PAID_QTY] numeric(18,2) NULL, [ETCIN_SEMI_PAID_AMT] numeric(18,2) NULL,
  [ETCIN_SEMI_FREE_QTY] numeric(18,2) NULL, [ETCIN_SEMI_FREE_AMT] numeric(18,2) NULL,
  [ETCIN_ETC_QTY] numeric(18,2) NULL, [ETCIN_ETC_AMT] numeric(18,2) NULL,
  [ETCIN_TOTAL_QTY] numeric(18,2) NULL, [ETCIN_TOTAL_AMT] numeric(18,2) NULL,
  [OUT_SHIP_A_PAID_QTY] numeric(18,2) NULL, [OUT_SHIP_A_PAID_AMT] numeric(18,2) NULL,
  [OUT_SHIP_A_FREE_QTY] numeric(18,2) NULL, [OUT_SHIP_A_FREE_AMT] numeric(18,2) NULL,
  [OUT_SHIP_B_QTY] numeric(18,2) NULL, [OUT_SHIP_B_AMT] numeric(18,2) NULL,
  [T_OUTPUT_QTY] numeric(18,2) NULL, [T_OUTPUT_AMT] numeric(18,2) NULL,
  [ETCOUT_RESORT_QTY] numeric(18,2) NULL, [ETCOUT_RESORT_AMT] numeric(18,2) NULL,
  [ETCOUT_REWORK_QTY] numeric(18,2) NULL, [ETCOUT_REWORK_AMT] numeric(18,2) NULL,
  [ETCOUT_FREESALE_QTY] numeric(18,2) NULL, [ETCOUT_FREESALE_AMT] numeric(18,2) NULL,
  [ETCOUT_ETC_QTY] numeric(18,2) NULL, [ETCOUT_ETC_AMT] numeric(18,2) NULL,
  [ETCOUT_TOTAL_QTY] numeric(18,2) NULL, [ETCOUT_TOTAL_AMT] numeric(18,2) NULL,
  [LOSS_QTY] numeric(18,2) NULL, [LOSS_AMT] numeric(18,2) NULL,
  [EOH_WH0006_QTY] numeric(18,2) NULL, [EOH_WH0006_AMT] numeric(18,2) NULL,
  VERIFY numeric(18,2) NULL, EDIT_USER varchar(50) NULL, EDIT_DT datetime NULL DEFAULT getdate(),
  CONSTRAINT PK_doi_vn_stco PRIMARY KEY (yyyymm, sel_code, 도우코드, division, EXPEN_SEL)
);
