/* 타시스템 > 매출정보 > 수출신고필증조회 (TAB070024) — 수출신고필증(EXP_PERMIT) 적재 조회. 원천 DOI_VN_IF_EXP_PERMIT
 *   정의서 응답 param 전체 기준(내부코드 *Seq 제외). 숫자(환율/수량/단가/금액)는 매퍼에서 TRY_CONVERT, 날짜는 YYYY-MM-DD. */
const { ValueType } = require('realgrid');

const grid = {
  options: {
    checkBar: { visible: false },
    display: { columnMovable: false, fitStyle: 'fill', emptyMessage: '조회된 데이터가 없습니다.', hscrollBar: true, showEmptyMessage: true },
    edit: { editable: false },
    footer: { visible: false },
    rowIndicator: { visible: true },
  },
  fields: [
    { fieldName: '사업부문', dataType: ValueType.TEXT },
    { fieldName: '수입통관일', dataType: ValueType.TEXT },
    { fieldName: '수입통관관리번호', dataType: ValueType.TEXT },
    { fieldName: '수입통관번호', dataType: ValueType.TEXT },
    { fieldName: '수출구분', dataType: ValueType.TEXT },
    { fieldName: '거래처', dataType: ValueType.TEXT },
    { fieldName: '거래처번호', dataType: ValueType.TEXT },
    { fieldName: '부서', dataType: ValueType.TEXT },
    { fieldName: '담당자', dataType: ValueType.TEXT },
    { fieldName: '수출결재방법', dataType: ValueType.TEXT },
    { fieldName: '진행', dataType: ValueType.TEXT },
    { fieldName: '매출진행', dataType: ValueType.TEXT },
    { fieldName: '통화', dataType: ValueType.TEXT },
    { fieldName: '환율', dataType: ValueType.NUMBER },
    { fieldName: '가격조건', dataType: ValueType.TEXT },
    { fieldName: '품명', dataType: ValueType.TEXT },
    { fieldName: '품번', dataType: ValueType.TEXT },
    { fieldName: '규격', dataType: ValueType.TEXT },
    { fieldName: '단위', dataType: ValueType.TEXT },
    { fieldName: '수량', dataType: ValueType.NUMBER },
    { fieldName: '판매단가', dataType: ValueType.NUMBER },
    { fieldName: '금액', dataType: ValueType.NUMBER },
    { fieldName: '원화판매단가', dataType: ValueType.NUMBER },
    { fieldName: '원화금액', dataType: ValueType.NUMBER },
    { fieldName: '판매금액', dataType: ValueType.NUMBER },
    { fieldName: '기타출고구분', dataType: ValueType.TEXT },
    { fieldName: 'Invoice원천번호', dataType: ValueType.TEXT },
    { fieldName: '원천번호', dataType: ValueType.TEXT },
    { fieldName: '원천관리번호', dataType: ValueType.TEXT },
    { fieldName: '특이사항', dataType: ValueType.TEXT },
    { fieldName: '품목특이사항', dataType: ValueType.TEXT },
  ],
  columns: [
    { name: '사업부문', fieldName: '사업부문', width: 110, header: { text: '사업부문' }, styleName: 'tc' },
    { name: '수입통관일', fieldName: '수입통관일', width: 100, header: { text: '수입통관일' }, styleName: 'tc' },
    { name: '수입통관관리번호', fieldName: '수입통관관리번호', width: 140, header: { text: '수입통관관리번호' }, styleName: 'tl' },
    { name: '수입통관번호', fieldName: '수입통관번호', width: 150, header: { text: '수입통관번호' }, styleName: 'tl' },
    { name: '수출구분', fieldName: '수출구분', width: 150, header: { text: '수출구분' }, styleName: 'tl' },
    { name: '거래처', fieldName: '거래처', width: 160, header: { text: '거래처' }, styleName: 'tl' },
    { name: '거래처번호', fieldName: '거래처번호', width: 110, header: { text: '거래처번호' }, styleName: 'tl' },
    { name: '부서', fieldName: '부서', width: 100, header: { text: '부서' }, styleName: 'tl' },
    { name: '담당자', fieldName: '담당자', width: 110, header: { text: '담당자' }, styleName: 'tl' },
    { name: '수출결재방법', fieldName: '수출결재방법', width: 110, header: { text: '수출결재방법' }, styleName: 'tc' },
    { name: '진행', fieldName: '진행', width: 90, header: { text: '진행' }, styleName: 'tc' },
    { name: '매출진행', fieldName: '매출진행', width: 90, header: { text: '매출진행' }, styleName: 'tc' },
    { name: '통화', fieldName: '통화', width: 70, header: { text: '통화' }, styleName: 'tc' },
    { name: '환율', fieldName: '환율', width: 90, header: { text: '환율' }, styleName: 'tr', numberFormat: '#,##0.00' },
    { name: '가격조건', fieldName: '가격조건', width: 90, header: { text: '가격조건' }, styleName: 'tc' },
    { name: '품명', fieldName: '품명', width: 200, header: { text: '품명' }, styleName: 'tl' },
    { name: '품번', fieldName: '품번', width: 120, header: { text: '품번' }, styleName: 'tl' },
    { name: '규격', fieldName: '규격', width: 160, header: { text: '규격' }, styleName: 'tl' },
    { name: '단위', fieldName: '단위', width: 60, header: { text: '단위' }, styleName: 'tc' },
    { name: '수량', fieldName: '수량', width: 100, header: { text: '수량' }, styleName: 'tr', numberFormat: '#,##0.###' },
    { name: '판매단가', fieldName: '판매단가', width: 100, header: { text: '판매단가' }, styleName: 'tr', numberFormat: '#,##0.####' },
    { name: '금액', fieldName: '금액', width: 110, header: { text: '금액' }, styleName: 'tr', numberFormat: '#,##0.##' },
    { name: '원화판매단가', fieldName: '원화판매단가', width: 110, header: { text: '원화판매단가' }, styleName: 'tr', numberFormat: '#,##0.##' },
    { name: '원화금액', fieldName: '원화금액', width: 120, header: { text: '원화금액' }, styleName: 'tr', numberFormat: '#,##0.##' },
    { name: '판매금액', fieldName: '판매금액', width: 120, header: { text: '판매금액' }, styleName: 'tr', numberFormat: '#,##0.##' },
    { name: '기타출고구분', fieldName: '기타출고구분', width: 110, header: { text: '기타출고구분' }, styleName: 'tc' },
    { name: 'Invoice원천번호', fieldName: 'Invoice원천번호', width: 130, header: { text: 'Invoice원천번호' }, styleName: 'tl' },
    { name: '원천번호', fieldName: '원천번호', width: 120, header: { text: '원천번호' }, styleName: 'tl' },
    { name: '원천관리번호', fieldName: '원천관리번호', width: 130, header: { text: '원천관리번호' }, styleName: 'tl' },
    { name: '특이사항', fieldName: '특이사항', width: 180, header: { text: '특이사항' }, styleName: 'tl' },
    { name: '품목특이사항', fieldName: '품목특이사항', width: 180, header: { text: '품목특이사항' }, styleName: 'tl' },
  ],
  layout: [
    '사업부문',
    '수입통관일',
    '수입통관관리번호',
    '수입통관번호',
    '수출구분',
    '거래처',
    '거래처번호',
    '부서',
    '담당자',
    '수출결재방법',
    '진행',
    '매출진행',
    '통화',
    '환율',
    '가격조건',
    '품명',
    '품번',
    '규격',
    '단위',
    '수량',
    '판매단가',
    '금액',
    '원화판매단가',
    '원화금액',
    '판매금액',
    '기타출고구분',
    'Invoice원천번호',
    '원천번호',
    '원천관리번호',
    '특이사항',
    '품목특이사항',
  ],
};
module.exports = grid;
