/* ============================================================
   DOI_STOCK 202608 — breakdown 2개 컬럼 정정 + RMA_AMT 반영
   DB : 도우제조원가시스템 (10.100.40.17,14233)

   전수 재대사(엑셀 창고수불(202608) 112행 × 23컬럼) 결과,
   21개 중 19개 컬럼과 헤드라인 4개는 전부 일치했고 아래 2개만 어긋났다.

   [1] 기타입고 — R 모델 8행이 전부 0 (엑셀 합 2,722)
       엑셀 18열(입고 그룹의 '기타입고')이 R 모델에서 반품입고 수량과 같은 값을 갖는다.
       소비처: UP_DOI_STOCK_COST (결산)
         7073R 71 / 7110R 97 / 8085R 10 / 810PR 58 / 8122R 148 / 8136R 1473 / 8140R 2 / 902KR 863

   [2] OUT_ETC — 7073R 1행이 0 (엑셀 258, 공정재투입)
       소비처: UP_DOI_STOCK_BOH, UP_DOI_STOCK_COST, DOI_ManufacturingCostOfWIP,
               DOI_ProdSubulMonthlyReport, DOI_StockExpenseByModel
       현재 DB는 7073R 이 OUT=258 인데 분해합이 0 이라 출고 항등식이 깨져 있다.
       정정하면 출고 항등식 위반은 7073P(+71) / 7110P(+97) 두 행만 남는데,
       이 둘은 엑셀 자체가 '기타출고 71/97 인데 출고수량 0' 인 원본 모순이라 정상이다.

   [3] RMA_AMT — 12번의 두 번째 배치가 반영되지 않아 여전히 0 이다.
       사용자 결정대로 202601 과 동일하게 8월 반품 95,257,838 을 반영한다.
       UP_DOI_STOCK_BOH STEP6 이 model_type LIKE '%R' 의 RMA_AMT 를 읽어
       doi_stco 양산행 OUTETC_AMT 로 기입한다.

   ※ 이 스크립트는 전부 UPDATE 이며 행을 추가/삭제하지 않는다(112행 유지).
   실행: 검증 통과 시 자동 COMMIT, 실패 시 자동 ROLLBACK
   ============================================================ */
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRAN;

DECLARE @c1 INT = 0, @c2 INT = 0, @c3 INT = 0;

/* ---------- [1] 기타입고 ---------- */
UPDATE DOI_STOCK SET 기타입고=  71 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'7073R' AND STOCK=N'완제품 창고'; SET @c1=@c1+@@ROWCOUNT;
UPDATE DOI_STOCK SET 기타입고=  97 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'7110R' AND STOCK=N'완제품 창고'; SET @c1=@c1+@@ROWCOUNT;
UPDATE DOI_STOCK SET 기타입고=  10 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'8085R' AND STOCK=N'완제품 창고'; SET @c1=@c1+@@ROWCOUNT;
UPDATE DOI_STOCK SET 기타입고=  58 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'810PR' AND STOCK=N'완제품 창고'; SET @c1=@c1+@@ROWCOUNT;
UPDATE DOI_STOCK SET 기타입고= 148 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'8122R' AND STOCK=N'완제품 창고'; SET @c1=@c1+@@ROWCOUNT;
UPDATE DOI_STOCK SET 기타입고=1473 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'8136R' AND STOCK=N'완제품 창고'; SET @c1=@c1+@@ROWCOUNT;
UPDATE DOI_STOCK SET 기타입고=   2 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'8140R' AND STOCK=N'완제품 창고'; SET @c1=@c1+@@ROWCOUNT;
UPDATE DOI_STOCK SET 기타입고= 863 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'902KR' AND STOCK=N'완제품 창고'; SET @c1=@c1+@@ROWCOUNT;

/* ---------- [2] OUT_ETC (7073R) ---------- */
UPDATE DOI_STOCK SET OUT_ETC = 258
 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'7073R' AND STOCK=N'완제품 창고';
SET @c2=@@ROWCOUNT;

/* ---------- [3] RMA_AMT ---------- */
UPDATE DOI_STOCK SET RMA_AMT= 3565861 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'7073R' AND [INPUT]=71;   SET @c3=@c3+@@ROWCOUNT;
UPDATE DOI_STOCK SET RMA_AMT= 1006207 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'7110R' AND [INPUT]=97;   SET @c3=@c3+@@ROWCOUNT;
UPDATE DOI_STOCK SET RMA_AMT=   54984 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'8085R' AND [INPUT]=10;   SET @c3=@c3+@@ROWCOUNT;
UPDATE DOI_STOCK SET RMA_AMT= 4685636 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'810PR' AND [INPUT]=58;   SET @c3=@c3+@@ROWCOUNT;
UPDATE DOI_STOCK SET RMA_AMT= 5417098 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'8122R' AND [INPUT]=148;  SET @c3=@c3+@@ROWCOUNT;
UPDATE DOI_STOCK SET RMA_AMT= 8189758 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'8136R' AND [INPUT]=1473; SET @c3=@c3+@@ROWCOUNT;
UPDATE DOI_STOCK SET RMA_AMT=    9100 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'8140R' AND [INPUT]=2;    SET @c3=@c3+@@ROWCOUNT;
UPDATE DOI_STOCK SET RMA_AMT=72329194 WHERE YYYYMM='202608' AND SITE='HQ' AND SEL_CODE='ACTUAL' AND MODEL_TYPE=N'902KR' AND [INPUT]=863;  SET @c3=@c3+@@ROWCOUNT;

/* ---------- 검증 ---------- */
DECLARE @ok BIT = 1, @msg NVARCHAR(2000) = N'';
DECLARE @etcin  INT = (SELECT SUM(ISNULL(기타입고,0)) FROM DOI_STOCK WHERE YYYYMM='202608' AND SITE='HQ');
DECLARE @outetc INT = (SELECT SUM(ISNULL(OUT_ETC,0))  FROM DOI_STOCK WHERE YYYYMM='202608' AND SITE='HQ');
DECLARE @rma NUMERIC(20,2) = (SELECT SUM(ISNULL(RMA_AMT,0)) FROM DOI_STOCK WHERE YYYYMM='202608' AND SITE='HQ');
DECLARE @tot INT = (SELECT COUNT(*) FROM DOI_STOCK WHERE YYYYMM='202608' AND SITE='HQ');
DECLARE @inbad INT = (SELECT COUNT(*) FROM DOI_STOCK WHERE YYYYMM='202608' AND SITE='HQ'
                       AND ISNULL(INPUT_PROD,0)+ISNULL(INPUT_MOVING,0)+ISNULL(INPUT_ETC,0) <> ISNULL([INPUT],0));
DECLARE @outbad INT = (SELECT COUNT(*) FROM DOI_STOCK WHERE YYYYMM='202608' AND SITE='HQ'
                       AND ISNULL(OUT_SHEET,0)+ISNULL(OUT_INVOICE,0)+ISNULL(OUT_MOVING,0)+ISNULL(OUT_ETC,0) <> ISNULL([OUT],0));

IF @c1 <> 8      BEGIN SET @ok=0; SET @msg=@msg+N'기타입고 UPDATE 8행 기대, 실제 '+CAST(@c1 AS NVARCHAR(10))+N'; '; END
IF @c2 <> 1      BEGIN SET @ok=0; SET @msg=@msg+N'OUT_ETC UPDATE 1행 기대, 실제 '+CAST(@c2 AS NVARCHAR(10))+N'; '; END
IF @c3 <> 8      BEGIN SET @ok=0; SET @msg=@msg+N'RMA_AMT UPDATE 8행 기대, 실제 '+CAST(@c3 AS NVARCHAR(10))+N'; '; END
IF @etcin <> 2722    BEGIN SET @ok=0; SET @msg=@msg+N'기타입고 합계 2722 기대, 실제 '+CAST(@etcin AS NVARCHAR(20))+N'; '; END
IF @outetc <> 3844   BEGIN SET @ok=0; SET @msg=@msg+N'OUT_ETC 합계 3844 기대, 실제 '+CAST(@outetc AS NVARCHAR(20))+N'; '; END
IF @rma <> 95257838  BEGIN SET @ok=0; SET @msg=@msg+N'RMA_AMT 합계 95,257,838 기대, 실제 '+CAST(@rma AS NVARCHAR(30))+N'; '; END
IF @tot <> 112       BEGIN SET @ok=0; SET @msg=@msg+N'행수 112 기대, 실제 '+CAST(@tot AS NVARCHAR(10))+N'; '; END
IF @inbad <> 0       BEGIN SET @ok=0; SET @msg=@msg+N'입고 항등식 위반 '+CAST(@inbad AS NVARCHAR(10))+N'행; '; END
IF @outbad <> 2      BEGIN SET @ok=0; SET @msg=@msg+N'출고 항등식 위반 2행(7073P/7110P, 엑셀 원본 모순) 기대, 실제 '+CAST(@outbad AS NVARCHAR(10))+N'행; '; END

IF @ok = 1
BEGIN
  COMMIT;
  SELECT N'DOI_STOCK breakdown 정정 완료' AS 결과,
         @c1 AS 기타입고행, @c2 AS OUT_ETC행, @c3 AS RMA행,
         @etcin AS 기타입고합, @outetc AS OUT_ETC합, @rma AS RMA합계,
         @inbad AS 입고위반, @outbad AS 출고위반;
  SELECT MODEL, MODEL_TYPE, STOCK, [INPUT], [OUT], 기타입고, OUT_ETC, RMA_AMT
    FROM DOI_STOCK WHERE YYYYMM='202608' AND SITE='HQ' AND MODEL_TYPE LIKE '%R'
   ORDER BY MODEL_TYPE;
END
ELSE
BEGIN
  ROLLBACK;
  SELECT N'검증 실패 — 원상복구' AS 결과, @msg AS 사유;
END
GO
