/*
 * VN_ProductCostLedger_Subul  (매출원가(제품)_VN / C0009007 TAB090016)
 *   원천 DOI_VN_STCO (도우코드 × 계정 그레인). 도우코드로 집계: 수량=MAX(반복), 금액=SUM.
 *   표시=모델(=도우코드)/구분(division). 컬럼 별칭은 프론트 CamelMap(fgLastMonth 등)과 매칭.
 *   OUTPUT SHIP(A급)은 PAID(유상)=OUT_SHIP_A_PAID, FREE(무상)=OUT_SHIP_A_FREE. 기타출고 RMA 없음.
 */
CREATE OR ALTER PROCEDURE VN_ProductCostLedger_Subul
( @YYYY VARCHAR(4)=NULL, @YYYYMM VARCHAR(6)=NULL, @SITE VARCHAR(4)=NULL, @SEL_CODE VARCHAR(10)='ACTUAL' )
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @SC VARCHAR(10)=ISNULL(NULLIF(@SEL_CODE,''),'ACTUAL');
    BEGIN TRY
        ;WITH a AS (
            SELECT 도우코드, MAX(division) division,
                MAX(ISNULL(BOH_QTY,0)) bohQ, SUM(ISNULL(BOH_AMT,0)) bohA,
                MAX(ISNULL(IN_NORMAL_LAST_QTY,0)) flQ, SUM(ISNULL(IN_NORMAL_LAST_AMT,0)) flA,
                MAX(ISNULL(IN_NORMAL_THIS_QTY,0)) ftQ, SUM(ISNULL(IN_NORMAL_THIS_AMT,0)) ftA,
                MAX(ISNULL(IN_RW_BACKSHIP_SORT_QTY,0)) bssQ, SUM(ISNULL(IN_RW_BACKSHIP_SORT_AMT,0)) bssA,
                MAX(ISNULL(IN_RW_BACKSHIP_PFRW_QTY,0)) bspQ, SUM(ISNULL(IN_RW_BACKSHIP_PFRW_AMT,0)) bspA,
                MAX(ISNULL(IN_RW_BACKSHIP_PLRW_QTY,0)) bslQ, SUM(ISNULL(IN_RW_BACKSHIP_PLRW_AMT,0)) bslA,
                MAX(ISNULL(IN_RW_WHRET_SORT_QTY,0)) wrsQ, SUM(ISNULL(IN_RW_WHRET_SORT_AMT,0)) wrsA,
                MAX(ISNULL(IN_RW_WHRET_PFRW_QTY,0)) wrpQ, SUM(ISNULL(IN_RW_WHRET_PFRW_AMT,0)) wrpA,
                MAX(ISNULL(IN_RW_WHRET_PLRW_QTY,0)) wrlQ, SUM(ISNULL(IN_RW_WHRET_PLRW_AMT,0)) wrlA,
                MAX(ISNULL(T_INPUT_QTY,0)) tiQ, SUM(ISNULL(T_INPUT_AMT,0)) tiA,
                MAX(ISNULL(ETCIN_RMA_QTY,0)) irmQ, SUM(ISNULL(ETCIN_RMA_AMT,0)) irmA,
                MAX(ISNULL(ETCIN_SEMI_PAID_QTY,0)) ispQ, SUM(ISNULL(ETCIN_SEMI_PAID_AMT,0)) ispA,
                MAX(ISNULL(ETCIN_SEMI_FREE_QTY,0)) isfQ, SUM(ISNULL(ETCIN_SEMI_FREE_AMT,0)) isfA,
                MAX(ISNULL(ETCIN_ETC_QTY,0)) ioQ, SUM(ISNULL(ETCIN_ETC_AMT,0)) ioA,
                MAX(ISNULL(ETCIN_TOTAL_QTY,0)) itQ, SUM(ISNULL(ETCIN_TOTAL_AMT,0)) itA,
                MAX(ISNULL(OUT_SHIP_A_PAID_QTY,0)) saQ, SUM(ISNULL(OUT_SHIP_A_PAID_AMT,0)) saA,
                MAX(ISNULL(OUT_SHIP_A_FREE_QTY,0)) safQ, SUM(ISNULL(OUT_SHIP_A_FREE_AMT,0)) safA,
                MAX(ISNULL(OUT_SHIP_B_QTY,0)) sbQ, SUM(ISNULL(OUT_SHIP_B_AMT,0)) sbA,
                MAX(ISNULL(T_OUTPUT_QTY,0)) toQ, SUM(ISNULL(T_OUTPUT_AMT,0)) toA,
                MAX(ISNULL(ETCOUT_RESORT_QTY,0)) orsQ, SUM(ISNULL(ETCOUT_RESORT_AMT,0)) orsA,
                MAX(ISNULL(ETCOUT_REWORK_QTY,0)) orwQ, SUM(ISNULL(ETCOUT_REWORK_AMT,0)) orwA,
                MAX(ISNULL(ETCOUT_FREESALE_QTY,0)) ofsQ, SUM(ISNULL(ETCOUT_FREESALE_AMT,0)) ofsA,
                MAX(ISNULL(ETCOUT_ETC_QTY,0)) ooQ, SUM(ISNULL(ETCOUT_ETC_AMT,0)) ooA,
                MAX(ISNULL(ETCOUT_TOTAL_QTY,0)) otQ, SUM(ISNULL(ETCOUT_TOTAL_AMT,0)) otA,
                MAX(ISNULL(LOSS_QTY,0)) lQ, SUM(ISNULL(LOSS_AMT,0)) lA,
                MAX(ISNULL(EOH_WH0006_QTY,0)) eQ, SUM(ISNULL(EOH_WH0006_AMT,0)) eA
            FROM DOI_VN_STCO WITH(NOLOCK)
            WHERE SEL_CODE=@SC
              AND ( (NULLIF(@YYYYMM,'') IS NOT NULL AND YYYYMM=@YYYYMM)
                 OR (NULLIF(@YYYYMM,'') IS NULL AND SUBSTRING(YYYYMM,1,4)=@YYYY) )
              AND 도우코드 IS NOT NULL AND LTRIM(RTRIM(도우코드))<>'' AND 도우코드 <> N'TOTAL'
            GROUP BY 도우코드
        )
        SELECT
              도우코드 AS MODEL, division AS DIVISION
            , bohQ AS BOH_QTY, bohA AS BOH_AMT
            , flQ AS FG_LAST_MONTH_QTY, flA AS FG_LAST_MONTH_AMT
            , ftQ AS FG_THIS_MONTH_QTY, ftA AS FG_THIS_MONTH_AMT
            , bssQ AS BACK_SHIP_SORTING_QTY, bssA AS BACK_SHIP_SORTING_AMT
            , bspQ AS BACK_SHIP_PF_RW_QTY,   bspA AS BACK_SHIP_PF_RW_AMT
            , bslQ AS BACK_SHIP_PL_RW_QTY,   bslA AS BACK_SHIP_PL_RW_AMT
            , wrsQ AS WH_RETURN_SORTING_QTY, wrsA AS WH_RETURN_SORTING_AMT
            , wrpQ AS WH_RETURN_PF_RW_QTY,   wrpA AS WH_RETURN_PF_RW_AMT
            , wrlQ AS WH_RETURN_PL_RW_QTY,   wrlA AS WH_RETURN_PL_RW_AMT
            , tiQ AS T_INPUT_QTY, tiA AS T_INPUT_AMT
            , irmQ AS IE_RMA_QTY, irmA AS IE_RMA_AMT
            , ispQ AS IE_RETURN_PAID_QTY, ispA AS IE_RETURN_PAID_AMT
            , isfQ AS IE_RETURN_FREE_QTY, isfA AS IE_RETURN_FREE_AMT
            , ioQ AS IE_OTHER_QTY, ioA AS IE_OTHER_AMT
            , itQ AS IE_TOTAL_QTY, itA AS IE_TOTAL_AMT
            , saQ AS SHIP_A_PAID_QTY, saA AS SHIP_A_PAID_AMT
            , safQ AS SHIP_A_FREE_QTY, safA AS SHIP_A_FREE_AMT
            , sbQ AS SHIP_B_PAID_QTY, sbA AS SHIP_B_PAID_AMT
            , toQ AS T_OUTPUT_QTY, toA AS T_OUTPUT_AMT
            , orsQ AS OE_RESORTING_QTY, orsA AS OE_RESORTING_AMT
            , orwQ AS OE_REWORK_QTY,    orwA AS OE_REWORK_AMT
            , ofsQ AS OE_FREE_SALE_QTY, ofsA AS OE_FREE_SALE_AMT
            , ooQ AS OE_OTHER_QTY, ooA AS OE_OTHER_AMT
            , otQ AS OE_TOTAL_QTY, otA AS OE_TOTAL_AMT
            , lQ AS LOSS_QTY, lA AS LOSS_AMT
            , eQ AS EOH_QTY, eA AS EOH_AMT
        FROM a
        ORDER BY division, 도우코드;
    END TRY
    BEGIN CATCH
        SELECT ERROR_MESSAGE() AS ErrorMessage;
    END CATCH
END;
