/*
 * VN_ProductCostLedger_Subul (매출원가(제품)_VN / C0009007 TAB090016)
 *   결산 DOI_STCO(도우모델) 그대로, 화면에서 DOI_STOCK/BOH.MODEL_TYPE(=도우코드)로 매핑.
 *   @YYYYMM 있으면 해당월, 없으면 @YYYY 연 전체. @SEL_CODE 선택. 구조 스텁(측정값 0).
 */
CREATE OR ALTER PROCEDURE VN_ProductCostLedger_Subul
( @YYYY VARCHAR(4)=NULL, @YYYYMM VARCHAR(6)=NULL, @SITE VARCHAR(4)=NULL, @SEL_CODE VARCHAR(10)='ACTUAL' )
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @SC VARCHAR(10)=ISNULL(NULLIF(@SEL_CODE,''),'ACTUAL');
    BEGIN TRY
        ;WITH mt AS (
            SELECT DISTINCT MODEL, MODEL_TYPE FROM DOI_STOCK WITH(NOLOCK)
             WHERE SITE=@SITE AND SEL_CODE=@SC AND ( (NULLIF(@YYYYMM,'') IS NOT NULL AND YYYYMM=@YYYYMM) OR (NULLIF(@YYYYMM,'') IS NULL AND SUBSTRING(YYYYMM,1,4)=@YYYY) ) AND MODEL_TYPE IS NOT NULL AND LTRIM(RTRIM(MODEL_TYPE))<>''
            UNION
            SELECT DISTINCT model, model_type FROM DOI_STOCK_BOH WITH(NOLOCK)
             WHERE SITE=@SITE AND sel_code=@SC AND ( (NULLIF(@YYYYMM,'') IS NOT NULL AND yyyymm=@YYYYMM) OR (NULLIF(@YYYYMM,'') IS NULL AND SUBSTRING(yyyymm,1,4)=@YYYY) ) AND model_type IS NOT NULL AND LTRIM(RTRIM(model_type))<>''
        ),
        stco AS (
            SELECT DISTINCT MODEL FROM DOI_STCO WITH(NOLOCK)
             WHERE SITE=@SITE AND SEL_CODE=@SC AND ( (NULLIF(@YYYYMM,'') IS NOT NULL AND YYYYMM=@YYYYMM) OR (NULLIF(@YYYYMM,'') IS NULL AND SUBSTRING(YYYYMM,1,4)=@YYYY) )
        )
        SELECT DISTINCT
              COALESCE(mt.MODEL_TYPE, s.MODEL) AS MODEL
            , CASE WHEN RIGHT(RTRIM(COALESCE(mt.MODEL_TYPE,s.MODEL)),1)=N'P' THEN N'MP' ELSE N'R&D' END AS DIVISION
            , CAST(0 AS DECIMAL(18,2)) AS BOH_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_AMT
            , CAST(0 AS DECIMAL(18,2)) AS FG_LAST_MONTH_QTY
            , CAST(0 AS DECIMAL(18,2)) AS FG_LAST_MONTH_AMT
            , CAST(0 AS DECIMAL(18,2)) AS FG_THIS_MONTH_QTY
            , CAST(0 AS DECIMAL(18,2)) AS FG_THIS_MONTH_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_SORTING_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_SORTING_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_PF_RW_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_PF_RW_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_PL_RW_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_PL_RW_AMT
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_SORTING_QTY
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_SORTING_AMT
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_PF_RW_QTY
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_PF_RW_AMT
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_PL_RW_QTY
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_PL_RW_AMT
            , CAST(0 AS DECIMAL(18,2)) AS T_INPUT_QTY
            , CAST(0 AS DECIMAL(18,2)) AS T_INPUT_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IE_RMA_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IE_RMA_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IE_RETURN_PAID_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IE_RETURN_PAID_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IE_RETURN_FREE_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IE_RETURN_FREE_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IE_OTHER_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IE_OTHER_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IE_TOTAL_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IE_TOTAL_AMT
            , CAST(0 AS DECIMAL(18,2)) AS SHIP_A_PAID_QTY
            , CAST(0 AS DECIMAL(18,2)) AS SHIP_A_PAID_AMT
            , CAST(0 AS DECIMAL(18,2)) AS SHIP_B_PAID_QTY
            , CAST(0 AS DECIMAL(18,2)) AS SHIP_B_PAID_AMT
            , CAST(0 AS DECIMAL(18,2)) AS T_OUTPUT_QTY
            , CAST(0 AS DECIMAL(18,2)) AS T_OUTPUT_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_RESORTING_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_RESORTING_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_REWORK_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_REWORK_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_RMA_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_RMA_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_FREE_SALE_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_FREE_SALE_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_OTHER_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_OTHER_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_TOTAL_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_TOTAL_AMT
            , CAST(0 AS DECIMAL(18,2)) AS LOSS_QTY
            , CAST(0 AS DECIMAL(18,2)) AS LOSS_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_AMT
        FROM stco s
        LEFT JOIN mt ON mt.MODEL = s.MODEL
        ORDER BY CASE WHEN RIGHT(RTRIM(COALESCE(mt.MODEL_TYPE,s.MODEL)),1)=N'P' THEN N'MP' ELSE N'R&D' END, COALESCE(mt.MODEL_TYPE, s.MODEL);
    END TRY
    BEGIN CATCH SELECT ERROR_MESSAGE() AS ErrorMessage; END CATCH
END;
