/*
 * VN_ProductCostLedger_Subul  (매출원가(제품)_VN / C0009007 TAB090016)
 *   결산 DOI_STCO(도우모델 그레인)는 그대로 두고, 화면에서만 도우모델 -> 도우코드로 매핑.
 *   도우코드 = DOI_STOCK/DOI_STOCK_BOH 의 MODEL_TYPE(도우코드와 동일). 모델당 MODEL_TYPE 다중이면 전부 표시(fan-out).
 *   재고에 없는 모델은 도우모델을 그대로 표시(COALESCE 폴백).
 *   표시=모델(=도우코드)/구분(도우코드 끝자리 P->MP, 그 외 R&D).
 *   구조 스텁: 측정값 전부 0. 산식 추후 정의.
 */
CREATE OR ALTER PROCEDURE VN_ProductCostLedger_Subul
( @YYYYMM VARCHAR(6), @SITE VARCHAR(4) )
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        ;WITH mt AS (
            SELECT DISTINCT MODEL, MODEL_TYPE FROM DOI_STOCK WITH(NOLOCK)
             WHERE YYYYMM=@YYYYMM AND SITE=@SITE AND MODEL_TYPE IS NOT NULL AND LTRIM(RTRIM(MODEL_TYPE))<>''
            UNION
            SELECT DISTINCT model, model_type FROM DOI_STOCK_BOH WITH(NOLOCK)
             WHERE yyyymm=@YYYYMM AND SITE=@SITE AND model_type IS NOT NULL AND LTRIM(RTRIM(model_type))<>''
        ),
        stco AS (
            SELECT DISTINCT MODEL FROM DOI_STCO WITH(NOLOCK) WHERE YYYYMM=@YYYYMM AND SITE=@SITE
        )
        SELECT DISTINCT
              COALESCE(mt.MODEL_TYPE, s.MODEL) AS MODEL
            , CASE WHEN RIGHT(RTRIM(COALESCE(mt.MODEL_TYPE, s.MODEL)),1)=N'P' THEN N'MP' ELSE N'R&D' END AS DIVISION
            , CAST(0 AS DECIMAL(18,2)) AS BOH_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_AMT
            , CAST(0 AS DECIMAL(18,2)) AS FG_LAST_MONTH_QTY
            , CAST(0 AS DECIMAL(18,2)) AS FG_LAST_MONTH_AMT
            , CAST(0 AS DECIMAL(18,2)) AS FG_THIS_MONTH_QTY
            , CAST(0 AS DECIMAL(18,2)) AS FG_THIS_MONTH_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_SORTING_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_SORTING_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_PF_RW_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_PF_RW_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_PL_RW_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BACK_SHIP_PL_RW_AMT
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_SORTING_QTY
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_SORTING_AMT
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_PF_RW_QTY
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_PF_RW_AMT
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_PL_RW_QTY
            , CAST(0 AS DECIMAL(18,2)) AS WH_RETURN_PL_RW_AMT
            , CAST(0 AS DECIMAL(18,2)) AS T_INPUT_QTY
            , CAST(0 AS DECIMAL(18,2)) AS T_INPUT_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IE_RMA_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IE_RMA_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IE_RETURN_PAID_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IE_RETURN_PAID_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IE_RETURN_FREE_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IE_RETURN_FREE_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IE_OTHER_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IE_OTHER_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IE_TOTAL_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IE_TOTAL_AMT
            , CAST(0 AS DECIMAL(18,2)) AS SHIP_A_PAID_QTY
            , CAST(0 AS DECIMAL(18,2)) AS SHIP_A_PAID_AMT
            , CAST(0 AS DECIMAL(18,2)) AS SHIP_B_PAID_QTY
            , CAST(0 AS DECIMAL(18,2)) AS SHIP_B_PAID_AMT
            , CAST(0 AS DECIMAL(18,2)) AS T_OUTPUT_QTY
            , CAST(0 AS DECIMAL(18,2)) AS T_OUTPUT_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_RESORTING_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_RESORTING_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_REWORK_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_REWORK_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_RMA_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_RMA_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_FREE_SALE_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_FREE_SALE_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_OTHER_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_OTHER_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OE_TOTAL_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OE_TOTAL_AMT
            , CAST(0 AS DECIMAL(18,2)) AS LOSS_QTY
            , CAST(0 AS DECIMAL(18,2)) AS LOSS_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_AMT
        FROM stco s
        LEFT JOIN mt ON mt.MODEL = s.MODEL
        ORDER BY CASE WHEN RIGHT(RTRIM(COALESCE(mt.MODEL_TYPE, s.MODEL)),1)=N'P' THEN N'MP' ELSE N'R&D' END, COALESCE(mt.MODEL_TYPE, s.MODEL);
    END TRY
    BEGIN CATCH SELECT ERROR_MESSAGE() AS ErrorMessage; END CATCH
END;
