/*
 * VN_WipCostLedger_Subul (제조원가(재공)_VN / C0009007 TAB090017)
 *   소스 DOI_COST, 도우코드 그레인. 표시=모델(=도우코드)/구분(끝자리 P->MP, 그 외 R&D).
 *   @YYYYMM 있으면 해당월, 없으면 @YYYY 연 전체. @SEL_CODE 선택. 구조 스텁(측정값 0).
 */
CREATE OR ALTER PROCEDURE VN_WipCostLedger_Subul
( @YYYY VARCHAR(4)=NULL, @YYYYMM VARCHAR(6)=NULL, @SITE VARCHAR(4)=NULL, @SEL_CODE VARCHAR(10)='ACTUAL' )
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        SELECT
              도우코드 AS MODEL
            , CASE WHEN RIGHT(RTRIM(도우코드),1)=N'P' THEN N'MP' ELSE N'R&D' END AS DIVISION
            , CAST(0 AS DECIMAL(18,2)) AS BOH_LINE_WIP_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_LINE_WIP_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_LINE_WIP_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_LINE_WIP_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_LINE_FGS_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_LINE_FGS_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_LINE_FGS_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_LINE_FGS_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_A_SUB_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_A_SUB_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_A_SUB_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_A_SUB_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_WIP_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_WIP_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_WIP_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_WIP_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_FGS_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_FGS_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_FGS_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_FGS_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_SUB_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_SUB_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_SUB_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS BOH_B_SUB_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS T_BOH_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS T_BOH_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS T_BOH_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS T_BOH_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_LINE_WIP_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_LINE_WIP_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_LINE_WIP_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_LINE_WIP_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_LINE_FGS_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_LINE_FGS_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_LINE_FGS_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_LINE_FGS_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_B_WIP_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_B_WIP_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_B_WIP_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_B_WIP_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_B_FGS_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_B_FGS_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_B_FGS_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_B_FGS_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_T_WIP_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_T_WIP_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_T_WIP_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_T_WIP_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_T_FGS_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_T_FGS_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS EOH_T_FGS_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS EOH_T_FGS_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS TOTAL_EOH_B_QTY
            , CAST(0 AS DECIMAL(18,2)) AS TOTAL_EOH_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS TOTAL_EOH_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS TOTAL_EOH_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS USC_INPUT_QTY
            , CAST(0 AS DECIMAL(18,2)) AS USC_INPUT_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IN_CODE_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IN_CODE_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IN_RESORT_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IN_RESORT_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IN_REWORK_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IN_REWORK_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IN_SEMI_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IN_SEMI_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IN_ETC_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IN_ETC_AMT
            , CAST(0 AS DECIMAL(18,2)) AS IN_TOTAL_QTY
            , CAST(0 AS DECIMAL(18,2)) AS IN_TOTAL_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUTPUT_A_QTY
            , CAST(0 AS DECIMAL(18,2)) AS OUTPUT_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUT_CODE_B_QTY,      CAST(0 AS DECIMAL(18,2)) AS OUT_CODE_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUT_CODE_A_QTY,      CAST(0 AS DECIMAL(18,2)) AS OUT_CODE_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUT_SEMI_PAID_B_QTY, CAST(0 AS DECIMAL(18,2)) AS OUT_SEMI_PAID_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUT_SEMI_PAID_A_QTY, CAST(0 AS DECIMAL(18,2)) AS OUT_SEMI_PAID_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUT_SEMI_FREE_B_QTY, CAST(0 AS DECIMAL(18,2)) AS OUT_SEMI_FREE_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUT_SEMI_FREE_A_QTY, CAST(0 AS DECIMAL(18,2)) AS OUT_SEMI_FREE_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUT_ETC_B_QTY,       CAST(0 AS DECIMAL(18,2)) AS OUT_ETC_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUT_ETC_A_QTY,       CAST(0 AS DECIMAL(18,2)) AS OUT_ETC_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUT_TOTAL_B_QTY,     CAST(0 AS DECIMAL(18,2)) AS OUT_TOTAL_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS OUT_TOTAL_A_QTY,     CAST(0 AS DECIMAL(18,2)) AS OUT_TOTAL_A_AMT
            , CAST(0 AS DECIMAL(18,2)) AS LOSS_B_QTY, CAST(0 AS DECIMAL(18,2)) AS LOSS_B_AMT
            , CAST(0 AS DECIMAL(18,2)) AS LOSS_A_QTY, CAST(0 AS DECIMAL(18,2)) AS LOSS_A_AMT
        FROM DOI_COST WITH (NOLOCK)
        WHERE SITE=@SITE AND SEL_CODE=ISNULL(NULLIF(@SEL_CODE,''),'ACTUAL')
          AND ( (NULLIF(@YYYYMM,'') IS NOT NULL AND YYYYMM=@YYYYMM) OR (NULLIF(@YYYYMM,'') IS NULL AND SUBSTRING(YYYYMM,1,4)=@YYYY) )
          AND 도우코드 IS NOT NULL AND LTRIM(RTRIM(도우코드))<>''
        GROUP BY 도우코드
        ORDER BY CASE WHEN RIGHT(RTRIM(도우코드),1)=N'P' THEN N'MP' ELSE N'R&D' END, 도우코드;
    END TRY
    BEGIN CATCH SELECT ERROR_MESSAGE() AS ErrorMessage; END CATCH
END;
