/* 자재코드 → DOI_HQ_IF_MATERIAL (HQ 신규, txn=False) */
IF OBJECT_ID('DOI_HQ_IF_MATERIAL') IS NOT NULL DROP TABLE DOI_HQ_IF_MATERIAL;
CREATE TABLE DOI_HQ_IF_MATERIAL (
  [SITE] NVARCHAR(4),
  [LOAD_DTTM] DATETIME,
  [REQUEST_ID] NVARCHAR(50),
  [ItemSeq] NVARCHAR(200),
  [ItemName] NVARCHAR(200),
  [ItemNo] NVARCHAR(200),
  [Spec] NVARCHAR(200),
  [UnitSeq] NVARCHAR(200),
  [UnitName] NVARCHAR(200),
  [ProcRev] NVARCHAR(200),
  [ProcSeq] NVARCHAR(200),
  [ProcName] NVARCHAR(200),
  [AssyItemSeq] NVARCHAR(200),
  [AssyItemName] NVARCHAR(200),
  [AssyItemNo] NVARCHAR(200),
  [AssySpec] NVARCHAR(200),
  [AssyUnitSeq] NVARCHAR(200),
  [AssyUnitName] NVARCHAR(200),
  [AssyQtyNumerator] NVARCHAR(200),
  [AssyQtyDenominator] NVARCHAR(200),
  [AssyQty] NVARCHAR(200),
  [MatItemSeq] NVARCHAR(200),
  [MatItemName] NVARCHAR(200),
  [MatItemNo] NVARCHAR(200),
  [MatSpec] NVARCHAR(200),
  [MatUnitSeq] NVARCHAR(200),
  [MatUnitName] NVARCHAR(200),
  [STDUnitSeq] NVARCHAR(200),
  [StdUnitName] NVARCHAR(200),
  [MatQtyNum] NVARCHAR(200),
  [MatQtyDen] NVARCHAR(200),
  [MatQty] NVARCHAR(200),
  [STDQty] NVARCHAR(200),
  [InLossRate] NVARCHAR(200),
  [InLossMatQty] NVARCHAR(200),
  [OutLossRate] NVARCHAR(200),
  [OutLossMatQty] NVARCHAR(200),
  [LastUserSeq] NVARCHAR(200),
  [LastDateTime] NVARCHAR(200),
  [Remark] NVARCHAR(200),
  [Memo1] NVARCHAR(200),
  [Memo2] NVARCHAR(200),
  [Memo3] NVARCHAR(200),
  [SMDelvType] NVARCHAR(200),
  [SMDelvTypeName] NVARCHAR(200),
  [BizUnit] NVARCHAR(200),
  [BizUnitName] NVARCHAR(200),
  [UptEmpSeq] NVARCHAR(200),
  [UptEmpName] NVARCHAR(200),
  [UptDate] NVARCHAR(200),
  [Location] NVARCHAR(200),
  [MasterRemark] NVARCHAR(200),
  [SubItemProcRev] NVARCHAR(200),
  [UserNo] NVARCHAR(200),
  [ItemSerl] NVARCHAR(200),
  [RegEmpName] NVARCHAR(200),
  [RegDate] NVARCHAR(200),
  [AssetName] NVARCHAR(200),
  [UMItemClassLName] NVARCHAR(200),
  [UMItemClassMName] NVARCHAR(200),
  [UMItemClassName] NVARCHAR(200),
  [MatAssetName] NVARCHAR(200),
  [MatUMItemClassLName] NVARCHAR(200),
  [MatUMItemClassMName] NVARCHAR(200),
  [MatUMItemClassName] NVARCHAR(200),
  [TimeUnitName] NVARCHAR(200),
  [WorkHour] NVARCHAR(200),
  [MESProcSeq] NVARCHAR(200),
  [MESProcName] NVARCHAR(200),
  [RAW_JSON] NVARCHAR(MAX)
);

CREATE OR ALTER PROCEDURE UP_HQ_IF_LOAD_MATERIAL @json NVARCHAR(MAX), @requestId NVARCHAR(50)=NULL
AS
BEGIN
  SET NOCOUNT ON;
  DELETE FROM DOI_HQ_IF_MATERIAL WHERE SITE=N'HQ';
  INSERT INTO DOI_HQ_IF_MATERIAL ([SITE], [LOAD_DTTM], [REQUEST_ID], [ItemSeq], [ItemName], [ItemNo], [Spec], [UnitSeq], [UnitName], [ProcRev], [ProcSeq], [ProcName], [AssyItemSeq], [AssyItemName], [AssyItemNo], [AssySpec], [AssyUnitSeq], [AssyUnitName], [AssyQtyNumerator], [AssyQtyDenominator], [AssyQty], [MatItemSeq], [MatItemName], [MatItemNo], [MatSpec], [MatUnitSeq], [MatUnitName], [STDUnitSeq], [StdUnitName], [MatQtyNum], [MatQtyDen], [MatQty], [STDQty], [InLossRate], [InLossMatQty], [OutLossRate], [OutLossMatQty], [LastUserSeq], [LastDateTime], [Remark], [Memo1], [Memo2], [Memo3], [SMDelvType], [SMDelvTypeName], [BizUnit], [BizUnitName], [UptEmpSeq], [UptEmpName], [UptDate], [Location], [MasterRemark], [SubItemProcRev], [UserNo], [ItemSerl], [RegEmpName], [RegDate], [AssetName], [UMItemClassLName], [UMItemClassMName], [UMItemClassName], [MatAssetName], [MatUMItemClassLName], [MatUMItemClassMName], [MatUMItemClassName], [TimeUnitName], [WorkHour], [MESProcSeq], [MESProcName], [RAW_JSON])
  SELECT N'HQ', GETDATE(), @requestId, j.[ItemSeq], j.[ItemName], j.[ItemNo], j.[Spec], j.[UnitSeq], j.[UnitName], j.[ProcRev], j.[ProcSeq], j.[ProcName], j.[AssyItemSeq], j.[AssyItemName], j.[AssyItemNo], j.[AssySpec], j.[AssyUnitSeq], j.[AssyUnitName], j.[AssyQtyNumerator], j.[AssyQtyDenominator], j.[AssyQty], j.[MatItemSeq], j.[MatItemName], j.[MatItemNo], j.[MatSpec], j.[MatUnitSeq], j.[MatUnitName], j.[STDUnitSeq], j.[StdUnitName], j.[MatQtyNum], j.[MatQtyDen], j.[MatQty], j.[STDQty], j.[InLossRate], j.[InLossMatQty], j.[OutLossRate], j.[OutLossMatQty], j.[LastUserSeq], j.[LastDateTime], j.[Remark], j.[Memo1], j.[Memo2], j.[Memo3], j.[SMDelvType], j.[SMDelvTypeName], j.[BizUnit], j.[BizUnitName], j.[UptEmpSeq], j.[UptEmpName], j.[UptDate], j.[Location], j.[MasterRemark], j.[SubItemProcRev], j.[UserNo], j.[ItemSerl], j.[RegEmpName], j.[RegDate], j.[AssetName], j.[UMItemClassLName], j.[UMItemClassMName], j.[UMItemClassName], j.[MatAssetName], j.[MatUMItemClassLName], j.[MatUMItemClassMName], j.[MatUMItemClassName], j.[TimeUnitName], j.[WorkHour], j.[MESProcSeq], j.[MESProcName], j.[RAW_JSON]
  FROM OPENJSON(@json, '$.DataBlock1')
  WITH (
    [ItemSeq] NVARCHAR(200) '$."ItemSeq"',
    [ItemName] NVARCHAR(200) '$."ItemName"',
    [ItemNo] NVARCHAR(200) '$."ItemNo"',
    [Spec] NVARCHAR(200) '$."Spec"',
    [UnitSeq] NVARCHAR(200) '$."UnitSeq"',
    [UnitName] NVARCHAR(200) '$."UnitName"',
    [ProcRev] NVARCHAR(200) '$."ProcRev"',
    [ProcSeq] NVARCHAR(200) '$."ProcSeq"',
    [ProcName] NVARCHAR(200) '$."ProcName"',
    [AssyItemSeq] NVARCHAR(200) '$."AssyItemSeq"',
    [AssyItemName] NVARCHAR(200) '$."AssyItemName"',
    [AssyItemNo] NVARCHAR(200) '$."AssyItemNo"',
    [AssySpec] NVARCHAR(200) '$."AssySpec"',
    [AssyUnitSeq] NVARCHAR(200) '$."AssyUnitSeq"',
    [AssyUnitName] NVARCHAR(200) '$."AssyUnitName"',
    [AssyQtyNumerator] NVARCHAR(200) '$."AssyQtyNumerator"',
    [AssyQtyDenominator] NVARCHAR(200) '$."AssyQtyDenominator"',
    [AssyQty] NVARCHAR(200) '$."AssyQty"',
    [MatItemSeq] NVARCHAR(200) '$."MatItemSeq"',
    [MatItemName] NVARCHAR(200) '$."MatItemName"',
    [MatItemNo] NVARCHAR(200) '$."MatItemNo"',
    [MatSpec] NVARCHAR(200) '$."MatSpec"',
    [MatUnitSeq] NVARCHAR(200) '$."MatUnitSeq"',
    [MatUnitName] NVARCHAR(200) '$."MatUnitName"',
    [STDUnitSeq] NVARCHAR(200) '$."STDUnitSeq"',
    [StdUnitName] NVARCHAR(200) '$."StdUnitName"',
    [MatQtyNum] NVARCHAR(200) '$."MatQtyNum"',
    [MatQtyDen] NVARCHAR(200) '$."MatQtyDen"',
    [MatQty] NVARCHAR(200) '$."MatQty"',
    [STDQty] NVARCHAR(200) '$."STDQty"',
    [InLossRate] NVARCHAR(200) '$."InLossRate"',
    [InLossMatQty] NVARCHAR(200) '$."InLossMatQty"',
    [OutLossRate] NVARCHAR(200) '$."OutLossRate"',
    [OutLossMatQty] NVARCHAR(200) '$."OutLossMatQty"',
    [LastUserSeq] NVARCHAR(200) '$."LastUserSeq"',
    [LastDateTime] NVARCHAR(200) '$."LastDateTime"',
    [Remark] NVARCHAR(200) '$."Remark"',
    [Memo1] NVARCHAR(200) '$."Memo1"',
    [Memo2] NVARCHAR(200) '$."Memo2"',
    [Memo3] NVARCHAR(200) '$."Memo3"',
    [SMDelvType] NVARCHAR(200) '$."SMDelvType"',
    [SMDelvTypeName] NVARCHAR(200) '$."SMDelvTypeName"',
    [BizUnit] NVARCHAR(200) '$."BizUnit"',
    [BizUnitName] NVARCHAR(200) '$."BizUnitName"',
    [UptEmpSeq] NVARCHAR(200) '$."UptEmpSeq"',
    [UptEmpName] NVARCHAR(200) '$."UptEmpName"',
    [UptDate] NVARCHAR(200) '$."UptDate"',
    [Location] NVARCHAR(200) '$."Location"',
    [MasterRemark] NVARCHAR(200) '$."MasterRemark"',
    [SubItemProcRev] NVARCHAR(200) '$."SubItemProcRev"',
    [UserNo] NVARCHAR(200) '$."UserNo"',
    [ItemSerl] NVARCHAR(200) '$."ItemSerl"',
    [RegEmpName] NVARCHAR(200) '$."RegEmpName"',
    [RegDate] NVARCHAR(200) '$."RegDate"',
    [AssetName] NVARCHAR(200) '$."AssetName"',
    [UMItemClassLName] NVARCHAR(200) '$."UMItemClassLName"',
    [UMItemClassMName] NVARCHAR(200) '$."UMItemClassMName"',
    [UMItemClassName] NVARCHAR(200) '$."UMItemClassName"',
    [MatAssetName] NVARCHAR(200) '$."MatAssetName"',
    [MatUMItemClassLName] NVARCHAR(200) '$."MatUMItemClassLName"',
    [MatUMItemClassMName] NVARCHAR(200) '$."MatUMItemClassMName"',
    [MatUMItemClassName] NVARCHAR(200) '$."MatUMItemClassName"',
    [TimeUnitName] NVARCHAR(200) '$."TimeUnitName"',
    [WorkHour] NVARCHAR(200) '$."WorkHour"',
    [MESProcSeq] NVARCHAR(200) '$."MESProcSeq"',
    [MESProcName] NVARCHAR(200) '$."MESProcName"',
    [RAW_JSON] NVARCHAR(MAX) '$' AS JSON
  ) j;
  SELECT @@ROWCOUNT AS loaded;
END;