/* 매출정보-거래명세서 → DOI_HQ_IF_SALES (HQ 신규, txn=True) */
IF OBJECT_ID('DOI_HQ_IF_SALES') IS NOT NULL DROP TABLE DOI_HQ_IF_SALES;
CREATE TABLE DOI_HQ_IF_SALES (
  [SITE] NVARCHAR(4),
  [SEL_CODE] NVARCHAR(10),
  [LOAD_DTTM] DATETIME,
  [REQUEST_ID] NVARCHAR(50),
  [BizUnitName] NVARCHAR(200),
  [InvoiceSeq] NVARCHAR(200),
  [InvoiceDate] NVARCHAR(200),
  [InvoiceSerl] NVARCHAR(200),
  [InvoiceNo] NVARCHAR(200),
  [SMExpKind] NVARCHAR(200),
  [SMExpKindName] NVARCHAR(200),
  [UMOutKindName] NVARCHAR(200),
  [DeptName] NVARCHAR(200),
  [EmpName] NVARCHAR(200),
  [CustName] NVARCHAR(200),
  [CustNo] NVARCHAR(200),
  [CustSeq] NVARCHAR(200),
  [IsStockSales] NVARCHAR(200),
  [IsConsign] NVARCHAR(200),
  [ItemName] NVARCHAR(200),
  [ItemNo] NVARCHAR(200),
  [Spec] NVARCHAR(200),
  [UnitName] NVARCHAR(200),
  [CustPrice] NVARCHAR(200),
  [Qty] NVARCHAR(200),
  [IsInclusedVAT] NVARCHAR(200),
  [VATRate] NVARCHAR(200),
  [CurrSeq] NVARCHAR(200),
  [CurrName] NVARCHAR(200),
  [ExRate] NVARCHAR(200),
  [Price] NVARCHAR(200),
  [CurAmt] NVARCHAR(200),
  [CurVAT] NVARCHAR(200),
  [TotCurAmt] NVARCHAR(200),
  [DomAmt] NVARCHAR(200),
  [DomVAT] NVARCHAR(200),
  [TotDomAmt] NVARCHAR(200),
  [STDUnitName] NVARCHAR(200),
  [STDQty] NVARCHAR(200),
  [WHName] NVARCHAR(200),
  [RemarkM] NVARCHAR(200),
  [RemarkI] NVARCHAR(200),
  [SMProgressTypeName] NVARCHAR(200),
  [IsDelvCfm] NVARCHAR(200),
  [SMSalesCrtKind] NVARCHAR(200),
  [SMSalesCrtKindName] NVARCHAR(200),
  [BillCustSeq] NVARCHAR(200),
  [BillCustName] NVARCHAR(200),
  [SourceNo] NVARCHAR(200),
  [SourceRefNo] NVARCHAR(200),
  [IsReturn] NVARCHAR(200),
  [SalesQty] NVARCHAR(200),
  [SalesPrice] NVARCHAR(200),
  [CustItemName] NVARCHAR(200),
  [CustItemNo] NVARCHAR(200),
  [CustItemSpec] NVARCHAR(200),
  [UMEtcOutKind] NVARCHAR(200),
  [UMEtcOutKindName] NVARCHAR(200),
  [LotNo] NVARCHAR(200),
  [AssetName] NVARCHAR(200),
  [DVCondition] NVARCHAR(200),
  [DVPlace] NVARCHAR(200),
  [DVPlaceName] NVARCHAR(200),
  [BillAmt] NVARCHAR(200),
  [SMTransStatusName] NVARCHAR(200),
  [ItemClassSName] NVARCHAR(200),
  [ItemClassMName] NVARCHAR(200),
  [ItemClassLName] NVARCHAR(200),
  [BKCustName] NVARCHAR(200),
  [Dummy1] NVARCHAR(200),
  [Dummy2] NVARCHAR(200),
  [Dummy3] NVARCHAR(200),
  [Dummy4] NVARCHAR(200),
  [Dummy5] NVARCHAR(200),
  [Dummy6] NVARCHAR(200),
  [Dummy7] NVARCHAR(200),
  [Dummy8] NVARCHAR(200),
  [Dummy9] NVARCHAR(200),
  [Dummy10] NVARCHAR(200),
  [IsRetroactivity] NVARCHAR(200),
  [RetroactivityQty] NVARCHAR(200),
  [ChannelName] NVARCHAR(200),
  [Location] NVARCHAR(200),
  [PONo] NVARCHAR(200),
  [BizAddr] NVARCHAR(200),
  [SetInOutNo] NVARCHAR(200),
  [BizNo] NVARCHAR(200),
  [ItemDvDate] NVARCHAR(200),
  [RAW_JSON] NVARCHAR(MAX)
);

CREATE OR ALTER PROCEDURE UP_HQ_IF_LOAD_SALES @json NVARCHAR(MAX), @selCode NVARCHAR(10)=N'ACTUAL', @requestId NVARCHAR(50)=NULL
AS
BEGIN
  SET NOCOUNT ON;
  DELETE FROM DOI_HQ_IF_SALES WHERE SITE=N'HQ' AND SEL_CODE=@selCode;
  INSERT INTO DOI_HQ_IF_SALES ([SITE], [SEL_CODE], [LOAD_DTTM], [REQUEST_ID], [BizUnitName], [InvoiceSeq], [InvoiceDate], [InvoiceSerl], [InvoiceNo], [SMExpKind], [SMExpKindName], [UMOutKindName], [DeptName], [EmpName], [CustName], [CustNo], [CustSeq], [IsStockSales], [IsConsign], [ItemName], [ItemNo], [Spec], [UnitName], [CustPrice], [Qty], [IsInclusedVAT], [VATRate], [CurrSeq], [CurrName], [ExRate], [Price], [CurAmt], [CurVAT], [TotCurAmt], [DomAmt], [DomVAT], [TotDomAmt], [STDUnitName], [STDQty], [WHName], [RemarkM], [RemarkI], [SMProgressTypeName], [IsDelvCfm], [SMSalesCrtKind], [SMSalesCrtKindName], [BillCustSeq], [BillCustName], [SourceNo], [SourceRefNo], [IsReturn], [SalesQty], [SalesPrice], [CustItemName], [CustItemNo], [CustItemSpec], [UMEtcOutKind], [UMEtcOutKindName], [LotNo], [AssetName], [DVCondition], [DVPlace], [DVPlaceName], [BillAmt], [SMTransStatusName], [ItemClassSName], [ItemClassMName], [ItemClassLName], [BKCustName], [Dummy1], [Dummy2], [Dummy3], [Dummy4], [Dummy5], [Dummy6], [Dummy7], [Dummy8], [Dummy9], [Dummy10], [IsRetroactivity], [RetroactivityQty], [ChannelName], [Location], [PONo], [BizAddr], [SetInOutNo], [BizNo], [ItemDvDate], [RAW_JSON])
  SELECT N'HQ', @selCode, GETDATE(), @requestId, j.[BizUnitName], j.[InvoiceSeq], j.[InvoiceDate], j.[InvoiceSerl], j.[InvoiceNo], j.[SMExpKind], j.[SMExpKindName], j.[UMOutKindName], j.[DeptName], j.[EmpName], j.[CustName], j.[CustNo], j.[CustSeq], j.[IsStockSales], j.[IsConsign], j.[ItemName], j.[ItemNo], j.[Spec], j.[UnitName], j.[CustPrice], j.[Qty], j.[IsInclusedVAT], j.[VATRate], j.[CurrSeq], j.[CurrName], j.[ExRate], j.[Price], j.[CurAmt], j.[CurVAT], j.[TotCurAmt], j.[DomAmt], j.[DomVAT], j.[TotDomAmt], j.[STDUnitName], j.[STDQty], j.[WHName], j.[RemarkM], j.[RemarkI], j.[SMProgressTypeName], j.[IsDelvCfm], j.[SMSalesCrtKind], j.[SMSalesCrtKindName], j.[BillCustSeq], j.[BillCustName], j.[SourceNo], j.[SourceRefNo], j.[IsReturn], j.[SalesQty], j.[SalesPrice], j.[CustItemName], j.[CustItemNo], j.[CustItemSpec], j.[UMEtcOutKind], j.[UMEtcOutKindName], j.[LotNo], j.[AssetName], j.[DVCondition], j.[DVPlace], j.[DVPlaceName], j.[BillAmt], j.[SMTransStatusName], j.[ItemClassSName], j.[ItemClassMName], j.[ItemClassLName], j.[BKCustName], j.[Dummy1], j.[Dummy2], j.[Dummy3], j.[Dummy4], j.[Dummy5], j.[Dummy6], j.[Dummy7], j.[Dummy8], j.[Dummy9], j.[Dummy10], j.[IsRetroactivity], j.[RetroactivityQty], j.[ChannelName], j.[Location], j.[PONo], j.[BizAddr], j.[SetInOutNo], j.[BizNo], j.[ItemDvDate], j.[RAW_JSON]
  FROM OPENJSON(@json, '$.DataBlock1')
  WITH (
    [BizUnitName] NVARCHAR(200) '$."BizUnitName"',
    [InvoiceSeq] NVARCHAR(200) '$."InvoiceSeq"',
    [InvoiceDate] NVARCHAR(200) '$."InvoiceDate"',
    [InvoiceSerl] NVARCHAR(200) '$."InvoiceSerl"',
    [InvoiceNo] NVARCHAR(200) '$."InvoiceNo"',
    [SMExpKind] NVARCHAR(200) '$."SMExpKind"',
    [SMExpKindName] NVARCHAR(200) '$."SMExpKindName"',
    [UMOutKindName] NVARCHAR(200) '$."UMOutKindName"',
    [DeptName] NVARCHAR(200) '$."DeptName"',
    [EmpName] NVARCHAR(200) '$."EmpName"',
    [CustName] NVARCHAR(200) '$."CustName"',
    [CustNo] NVARCHAR(200) '$."CustNo"',
    [CustSeq] NVARCHAR(200) '$."CustSeq"',
    [IsStockSales] NVARCHAR(200) '$."IsStockSales"',
    [IsConsign] NVARCHAR(200) '$."IsConsign"',
    [ItemName] NVARCHAR(200) '$."ItemName"',
    [ItemNo] NVARCHAR(200) '$."ItemNo"',
    [Spec] NVARCHAR(200) '$."Spec"',
    [UnitName] NVARCHAR(200) '$."UnitName"',
    [CustPrice] NVARCHAR(200) '$."CustPrice"',
    [Qty] NVARCHAR(200) '$."Qty"',
    [IsInclusedVAT] NVARCHAR(200) '$."IsInclusedVAT"',
    [VATRate] NVARCHAR(200) '$."VATRate"',
    [CurrSeq] NVARCHAR(200) '$."CurrSeq"',
    [CurrName] NVARCHAR(200) '$."CurrName"',
    [ExRate] NVARCHAR(200) '$."ExRate"',
    [Price] NVARCHAR(200) '$."Price"',
    [CurAmt] NVARCHAR(200) '$."CurAmt"',
    [CurVAT] NVARCHAR(200) '$."CurVAT"',
    [TotCurAmt] NVARCHAR(200) '$."TotCurAmt"',
    [DomAmt] NVARCHAR(200) '$."DomAmt"',
    [DomVAT] NVARCHAR(200) '$."DomVAT"',
    [TotDomAmt] NVARCHAR(200) '$."TotDomAmt"',
    [STDUnitName] NVARCHAR(200) '$."STDUnitName"',
    [STDQty] NVARCHAR(200) '$."STDQty"',
    [WHName] NVARCHAR(200) '$."WHName"',
    [RemarkM] NVARCHAR(200) '$."RemarkM"',
    [RemarkI] NVARCHAR(200) '$."RemarkI"',
    [SMProgressTypeName] NVARCHAR(200) '$."SMProgressTypeName"',
    [IsDelvCfm] NVARCHAR(200) '$."IsDelvCfm"',
    [SMSalesCrtKind] NVARCHAR(200) '$."SMSalesCrtKind"',
    [SMSalesCrtKindName] NVARCHAR(200) '$."SMSalesCrtKindName"',
    [BillCustSeq] NVARCHAR(200) '$."BillCustSeq"',
    [BillCustName] NVARCHAR(200) '$."BillCustName"',
    [SourceNo] NVARCHAR(200) '$."SourceNo"',
    [SourceRefNo] NVARCHAR(200) '$."SourceRefNo"',
    [IsReturn] NVARCHAR(200) '$."IsReturn"',
    [SalesQty] NVARCHAR(200) '$."SalesQty"',
    [SalesPrice] NVARCHAR(200) '$."SalesPrice"',
    [CustItemName] NVARCHAR(200) '$."CustItemName"',
    [CustItemNo] NVARCHAR(200) '$."CustItemNo"',
    [CustItemSpec] NVARCHAR(200) '$."CustItemSpec"',
    [UMEtcOutKind] NVARCHAR(200) '$."UMEtcOutKind"',
    [UMEtcOutKindName] NVARCHAR(200) '$."UMEtcOutKindName"',
    [LotNo] NVARCHAR(200) '$."LotNo"',
    [AssetName] NVARCHAR(200) '$."AssetName"',
    [DVCondition] NVARCHAR(200) '$."DVCondition"',
    [DVPlace] NVARCHAR(200) '$."DVPlace"',
    [DVPlaceName] NVARCHAR(200) '$."DVPlaceName"',
    [BillAmt] NVARCHAR(200) '$."BillAmt"',
    [SMTransStatusName] NVARCHAR(200) '$."SMTransStatusName"',
    [ItemClassSName] NVARCHAR(200) '$."ItemClassSName"',
    [ItemClassMName] NVARCHAR(200) '$."ItemClassMName"',
    [ItemClassLName] NVARCHAR(200) '$."ItemClassLName"',
    [BKCustName] NVARCHAR(200) '$."BKCustName"',
    [Dummy1] NVARCHAR(200) '$."Dummy1"',
    [Dummy2] NVARCHAR(200) '$."Dummy2"',
    [Dummy3] NVARCHAR(200) '$."Dummy3"',
    [Dummy4] NVARCHAR(200) '$."Dummy4"',
    [Dummy5] NVARCHAR(200) '$."Dummy5"',
    [Dummy6] NVARCHAR(200) '$."Dummy6"',
    [Dummy7] NVARCHAR(200) '$."Dummy7"',
    [Dummy8] NVARCHAR(200) '$."Dummy8"',
    [Dummy9] NVARCHAR(200) '$."Dummy9"',
    [Dummy10] NVARCHAR(200) '$."Dummy10"',
    [IsRetroactivity] NVARCHAR(200) '$."IsRetroactivity"',
    [RetroactivityQty] NVARCHAR(200) '$."RetroactivityQty"',
    [ChannelName] NVARCHAR(200) '$."ChannelName"',
    [Location] NVARCHAR(200) '$."Location"',
    [PONo] NVARCHAR(200) '$."PONo"',
    [BizAddr] NVARCHAR(200) '$."BizAddr"',
    [SetInOutNo] NVARCHAR(200) '$."SetInOutNo"',
    [BizNo] NVARCHAR(200) '$."BizNo"',
    [ItemDvDate] NVARCHAR(200) '$."ItemDvDate"',
    [RAW_JSON] NVARCHAR(MAX) '$' AS JSON
  ) j;
  SELECT @@ROWCOUNT AS loaded;
END;