/* 매출정보-수출Invoice → DOI_HQ_IF_EXP_INVOICE (HQ 신규, txn=True) */
IF OBJECT_ID('DOI_HQ_IF_EXP_INVOICE') IS NOT NULL DROP TABLE DOI_HQ_IF_EXP_INVOICE;
CREATE TABLE DOI_HQ_IF_EXP_INVOICE (
  [SITE] NVARCHAR(4),
  [SEL_CODE] NVARCHAR(10),
  [LOAD_DTTM] DATETIME,
  [REQUEST_ID] NVARCHAR(50),
  [InvoiceSeq] NVARCHAR(200),
  [InvoiceSerl] NVARCHAR(200),
  [IsDelvCfm] NVARCHAR(200),
  [BizUnit] NVARCHAR(200),
  [BizUnitName] NVARCHAR(200),
  [InvoiceDate] NVARCHAR(200),
  [InvoiceNo] NVARCHAR(200),
  [InvoiceRefNo] NVARCHAR(200),
  [SMExpKind] NVARCHAR(200),
  [UMOutKind] NVARCHAR(200),
  [UMOutKindName] NVARCHAR(200),
  [SMExpKindName] NVARCHAR(200),
  [CustSeq] NVARCHAR(200),
  [CustName] NVARCHAR(200),
  [CurrSeq] NVARCHAR(200),
  [CurrName] NVARCHAR(200),
  [UMPriceTerm] NVARCHAR(200),
  [UMPriceTermName] NVARCHAR(200),
  [DeptSeq] NVARCHAR(200),
  [DeptName] NVARCHAR(200),
  [EmpSeq] NVARCHAR(200),
  [ExRate] NVARCHAR(200),
  [EmpName] NVARCHAR(200),
  [ItemSeq] NVARCHAR(200),
  [ItemName] NVARCHAR(200),
  [ItemNo] NVARCHAR(200),
  [Spec] NVARCHAR(200),
  [UnitSeq] NVARCHAR(200),
  [UnitName] NVARCHAR(200),
  [Qty] NVARCHAR(200),
  [Price] NVARCHAR(200),
  [ItemPrice] NVARCHAR(200),
  [CustPrice] NVARCHAR(200),
  [VATRate] NVARCHAR(200),
  [CurAmt] NVARCHAR(200),
  [CurVAT] NVARCHAR(200),
  [DomAmt] NVARCHAR(200),
  [DomVAT] NVARCHAR(200),
  [TotDomAmt] NVARCHAR(200),
  [RemarkM] NVARCHAR(200),
  [Remark] NVARCHAR(200),
  [StdUnitSeq] NVARCHAR(200),
  [StdUnitName] NVARCHAR(200),
  [StdQty] NVARCHAR(200),
  [WHName] NVARCHAR(200),
  [DVPlaceSeq] NVARCHAR(200),
  [DVPlaceName] NVARCHAR(200),
  [SMProgressTypeName] NVARCHAR(200),
  [IsStockSales] NVARCHAR(200),
  [IsSalesProc] NVARCHAR(200),
  [IsReturn] NVARCHAR(200),
  [IsWithSalesVat] NVARCHAR(200),
  [UMEtcOutKind] NVARCHAR(200),
  [UMEtcOutKindName] NVARCHAR(200),
  [LotNo] NVARCHAR(200),
  [GrossWeight] NVARCHAR(200),
  [NetWeight] NVARCHAR(200),
  [Volume] NVARCHAR(200),
  [Capacity] NVARCHAR(200),
  [ContainerNo] NVARCHAR(200),
  [CottonNo] NVARCHAR(200),
  [SerialNo] NVARCHAR(200),
  [SalesPrice] NVARCHAR(200),
  [ItemClassSSeq] NVARCHAR(200),
  [ItemClassSName] NVARCHAR(200),
  [ItemClassMSeq] NVARCHAR(200),
  [ItemClassMName] NVARCHAR(200),
  [ItemClassLSeq] NVARCHAR(200),
  [ItemClassLName] NVARCHAR(200),
  [PONo] NVARCHAR(200),
  [SourceRefNo] NVARCHAR(200),
  [SourceNo] NVARCHAR(200),
  [Dummy1] NVARCHAR(200),
  [Dummy2] NVARCHAR(200),
  [Dummy3] NVARCHAR(200),
  [Dummy4] NVARCHAR(200),
  [Dummy5] NVARCHAR(200),
  [Dummy6] NVARCHAR(200),
  [Dummy7] NVARCHAR(200),
  [Dummy8] NVARCHAR(200),
  [Dummy9] NVARCHAR(200),
  [Dummy10] NVARCHAR(200),
  [CustItemName] NVARCHAR(200),
  [CustItemNo] NVARCHAR(200),
  [CustItemSpec] NVARCHAR(200),
  [ItemEngName] NVARCHAR(200),
  [AddInfo] NVARCHAR(200),
  [AssetName] NVARCHAR(200),
  [ItemDVDate] NVARCHAR(200),
  [SMSalesProgTypeName] NVARCHAR(200),
  [WHSeq] NVARCHAR(200),
  [CustNo] NVARCHAR(200),
  [EndUser] NVARCHAR(200),
  [EndUserText] NVARCHAR(200),
  [EndUserName] NVARCHAR(200),
  [HSCode] NVARCHAR(200),
  [BKCustName] NVARCHAR(200),
  [NonSalesAmt] NVARCHAR(200),
  [NonSalesQty] NVARCHAR(200),
  [RAW_JSON] NVARCHAR(MAX)
);

CREATE OR ALTER PROCEDURE UP_HQ_IF_LOAD_EXP_INVOICE @json NVARCHAR(MAX), @selCode NVARCHAR(10)=N'ACTUAL', @requestId NVARCHAR(50)=NULL
AS
BEGIN
  SET NOCOUNT ON;
  DELETE FROM DOI_HQ_IF_EXP_INVOICE WHERE SITE=N'HQ' AND SEL_CODE=@selCode;
  INSERT INTO DOI_HQ_IF_EXP_INVOICE ([SITE], [SEL_CODE], [LOAD_DTTM], [REQUEST_ID], [InvoiceSeq], [InvoiceSerl], [IsDelvCfm], [BizUnit], [BizUnitName], [InvoiceDate], [InvoiceNo], [InvoiceRefNo], [SMExpKind], [UMOutKind], [UMOutKindName], [SMExpKindName], [CustSeq], [CustName], [CurrSeq], [CurrName], [UMPriceTerm], [UMPriceTermName], [DeptSeq], [DeptName], [EmpSeq], [ExRate], [EmpName], [ItemSeq], [ItemName], [ItemNo], [Spec], [UnitSeq], [UnitName], [Qty], [Price], [ItemPrice], [CustPrice], [VATRate], [CurAmt], [CurVAT], [DomAmt], [DomVAT], [TotDomAmt], [RemarkM], [Remark], [StdUnitSeq], [StdUnitName], [StdQty], [WHName], [DVPlaceSeq], [DVPlaceName], [SMProgressTypeName], [IsStockSales], [IsSalesProc], [IsReturn], [IsWithSalesVat], [UMEtcOutKind], [UMEtcOutKindName], [LotNo], [GrossWeight], [NetWeight], [Volume], [Capacity], [ContainerNo], [CottonNo], [SerialNo], [SalesPrice], [ItemClassSSeq], [ItemClassSName], [ItemClassMSeq], [ItemClassMName], [ItemClassLSeq], [ItemClassLName], [PONo], [SourceRefNo], [SourceNo], [Dummy1], [Dummy2], [Dummy3], [Dummy4], [Dummy5], [Dummy6], [Dummy7], [Dummy8], [Dummy9], [Dummy10], [CustItemName], [CustItemNo], [CustItemSpec], [ItemEngName], [AddInfo], [AssetName], [ItemDVDate], [SMSalesProgTypeName], [WHSeq], [CustNo], [EndUser], [EndUserText], [EndUserName], [HSCode], [BKCustName], [NonSalesAmt], [NonSalesQty], [RAW_JSON])
  SELECT N'HQ', @selCode, GETDATE(), @requestId, j.[InvoiceSeq], j.[InvoiceSerl], j.[IsDelvCfm], j.[BizUnit], j.[BizUnitName], j.[InvoiceDate], j.[InvoiceNo], j.[InvoiceRefNo], j.[SMExpKind], j.[UMOutKind], j.[UMOutKindName], j.[SMExpKindName], j.[CustSeq], j.[CustName], j.[CurrSeq], j.[CurrName], j.[UMPriceTerm], j.[UMPriceTermName], j.[DeptSeq], j.[DeptName], j.[EmpSeq], j.[ExRate], j.[EmpName], j.[ItemSeq], j.[ItemName], j.[ItemNo], j.[Spec], j.[UnitSeq], j.[UnitName], j.[Qty], j.[Price], j.[ItemPrice], j.[CustPrice], j.[VATRate], j.[CurAmt], j.[CurVAT], j.[DomAmt], j.[DomVAT], j.[TotDomAmt], j.[RemarkM], j.[Remark], j.[StdUnitSeq], j.[StdUnitName], j.[StdQty], j.[WHName], j.[DVPlaceSeq], j.[DVPlaceName], j.[SMProgressTypeName], j.[IsStockSales], j.[IsSalesProc], j.[IsReturn], j.[IsWithSalesVat], j.[UMEtcOutKind], j.[UMEtcOutKindName], j.[LotNo], j.[GrossWeight], j.[NetWeight], j.[Volume], j.[Capacity], j.[ContainerNo], j.[CottonNo], j.[SerialNo], j.[SalesPrice], j.[ItemClassSSeq], j.[ItemClassSName], j.[ItemClassMSeq], j.[ItemClassMName], j.[ItemClassLSeq], j.[ItemClassLName], j.[PONo], j.[SourceRefNo], j.[SourceNo], j.[Dummy1], j.[Dummy2], j.[Dummy3], j.[Dummy4], j.[Dummy5], j.[Dummy6], j.[Dummy7], j.[Dummy8], j.[Dummy9], j.[Dummy10], j.[CustItemName], j.[CustItemNo], j.[CustItemSpec], j.[ItemEngName], j.[AddInfo], j.[AssetName], j.[ItemDVDate], j.[SMSalesProgTypeName], j.[WHSeq], j.[CustNo], j.[EndUser], j.[EndUserText], j.[EndUserName], j.[HSCode], j.[BKCustName], j.[NonSalesAmt], j.[NonSalesQty], j.[RAW_JSON]
  FROM OPENJSON(@json, '$.DataBlock1')
  WITH (
    [InvoiceSeq] NVARCHAR(200) '$."InvoiceSeq"',
    [InvoiceSerl] NVARCHAR(200) '$."InvoiceSerl"',
    [IsDelvCfm] NVARCHAR(200) '$."IsDelvCfm"',
    [BizUnit] NVARCHAR(200) '$."BizUnit"',
    [BizUnitName] NVARCHAR(200) '$."BizUnitName"',
    [InvoiceDate] NVARCHAR(200) '$."InvoiceDate"',
    [InvoiceNo] NVARCHAR(200) '$."InvoiceNo"',
    [InvoiceRefNo] NVARCHAR(200) '$."InvoiceRefNo"',
    [SMExpKind] NVARCHAR(200) '$."SMExpKind"',
    [UMOutKind] NVARCHAR(200) '$."UMOutKind"',
    [UMOutKindName] NVARCHAR(200) '$."UMOutKindName"',
    [SMExpKindName] NVARCHAR(200) '$."SMExpKindName"',
    [CustSeq] NVARCHAR(200) '$."CustSeq"',
    [CustName] NVARCHAR(200) '$."CustName"',
    [CurrSeq] NVARCHAR(200) '$."CurrSeq"',
    [CurrName] NVARCHAR(200) '$."CurrName"',
    [UMPriceTerm] NVARCHAR(200) '$."UMPriceTerm"',
    [UMPriceTermName] NVARCHAR(200) '$."UMPriceTermName"',
    [DeptSeq] NVARCHAR(200) '$."DeptSeq"',
    [DeptName] NVARCHAR(200) '$."DeptName"',
    [EmpSeq] NVARCHAR(200) '$."EmpSeq"',
    [ExRate] NVARCHAR(200) '$."ExRate"',
    [EmpName] NVARCHAR(200) '$."EmpName"',
    [ItemSeq] NVARCHAR(200) '$."ItemSeq"',
    [ItemName] NVARCHAR(200) '$."ItemName"',
    [ItemNo] NVARCHAR(200) '$."ItemNo"',
    [Spec] NVARCHAR(200) '$."Spec"',
    [UnitSeq] NVARCHAR(200) '$."UnitSeq"',
    [UnitName] NVARCHAR(200) '$."UnitName"',
    [Qty] NVARCHAR(200) '$."Qty"',
    [Price] NVARCHAR(200) '$."Price"',
    [ItemPrice] NVARCHAR(200) '$."ItemPrice"',
    [CustPrice] NVARCHAR(200) '$."CustPrice"',
    [VATRate] NVARCHAR(200) '$."VATRate"',
    [CurAmt] NVARCHAR(200) '$."CurAmt"',
    [CurVAT] NVARCHAR(200) '$."CurVAT"',
    [DomAmt] NVARCHAR(200) '$."DomAmt"',
    [DomVAT] NVARCHAR(200) '$."DomVAT"',
    [TotDomAmt] NVARCHAR(200) '$."TotDomAmt"',
    [RemarkM] NVARCHAR(200) '$."RemarkM"',
    [Remark] NVARCHAR(200) '$."Remark"',
    [StdUnitSeq] NVARCHAR(200) '$."StdUnitSeq"',
    [StdUnitName] NVARCHAR(200) '$."StdUnitName"',
    [StdQty] NVARCHAR(200) '$."StdQty"',
    [WHName] NVARCHAR(200) '$."WHName"',
    [DVPlaceSeq] NVARCHAR(200) '$."DVPlaceSeq"',
    [DVPlaceName] NVARCHAR(200) '$."DVPlaceName"',
    [SMProgressTypeName] NVARCHAR(200) '$."SMProgressTypeName"',
    [IsStockSales] NVARCHAR(200) '$."IsStockSales"',
    [IsSalesProc] NVARCHAR(200) '$."IsSalesProc"',
    [IsReturn] NVARCHAR(200) '$."IsReturn"',
    [IsWithSalesVat] NVARCHAR(200) '$."IsWithSalesVat"',
    [UMEtcOutKind] NVARCHAR(200) '$."UMEtcOutKind"',
    [UMEtcOutKindName] NVARCHAR(200) '$."UMEtcOutKindName"',
    [LotNo] NVARCHAR(200) '$."LotNo"',
    [GrossWeight] NVARCHAR(200) '$."GrossWeight"',
    [NetWeight] NVARCHAR(200) '$."NetWeight"',
    [Volume] NVARCHAR(200) '$."Volume"',
    [Capacity] NVARCHAR(200) '$."Capacity"',
    [ContainerNo] NVARCHAR(200) '$."ContainerNo"',
    [CottonNo] NVARCHAR(200) '$."CottonNo"',
    [SerialNo] NVARCHAR(200) '$."SerialNo"',
    [SalesPrice] NVARCHAR(200) '$."SalesPrice"',
    [ItemClassSSeq] NVARCHAR(200) '$."ItemClassSSeq"',
    [ItemClassSName] NVARCHAR(200) '$."ItemClassSName"',
    [ItemClassMSeq] NVARCHAR(200) '$."ItemClassMSeq"',
    [ItemClassMName] NVARCHAR(200) '$."ItemClassMName"',
    [ItemClassLSeq] NVARCHAR(200) '$."ItemClassLSeq"',
    [ItemClassLName] NVARCHAR(200) '$."ItemClassLName"',
    [PONo] NVARCHAR(200) '$."PONo"',
    [SourceRefNo] NVARCHAR(200) '$."SourceRefNo"',
    [SourceNo] NVARCHAR(200) '$."SourceNo"',
    [Dummy1] NVARCHAR(200) '$."Dummy1"',
    [Dummy2] NVARCHAR(200) '$."Dummy2"',
    [Dummy3] NVARCHAR(200) '$."Dummy3"',
    [Dummy4] NVARCHAR(200) '$."Dummy4"',
    [Dummy5] NVARCHAR(200) '$."Dummy5"',
    [Dummy6] NVARCHAR(200) '$."Dummy6"',
    [Dummy7] NVARCHAR(200) '$."Dummy7"',
    [Dummy8] NVARCHAR(200) '$."Dummy8"',
    [Dummy9] NVARCHAR(200) '$."Dummy9"',
    [Dummy10] NVARCHAR(200) '$."Dummy10"',
    [CustItemName] NVARCHAR(200) '$."CustItemName"',
    [CustItemNo] NVARCHAR(200) '$."CustItemNo"',
    [CustItemSpec] NVARCHAR(200) '$."CustItemSpec"',
    [ItemEngName] NVARCHAR(200) '$."ItemEngName"',
    [AddInfo] NVARCHAR(200) '$."AddInfo"',
    [AssetName] NVARCHAR(200) '$."AssetName"',
    [ItemDVDate] NVARCHAR(200) '$."ItemDVDate"',
    [SMSalesProgTypeName] NVARCHAR(200) '$."SMSalesProgTypeName"',
    [WHSeq] NVARCHAR(200) '$."WHSeq"',
    [CustNo] NVARCHAR(200) '$."CustNo"',
    [EndUser] NVARCHAR(200) '$."EndUser"',
    [EndUserText] NVARCHAR(200) '$."EndUserText"',
    [EndUserName] NVARCHAR(200) '$."EndUserName"',
    [HSCode] NVARCHAR(200) '$."HSCode"',
    [BKCustName] NVARCHAR(200) '$."BKCustName"',
    [NonSalesAmt] NVARCHAR(200) '$."NonSalesAmt"',
    [NonSalesQty] NVARCHAR(200) '$."NonSalesQty"',
    [RAW_JSON] NVARCHAR(MAX) '$' AS JSON
  ) j;
  SELECT @@ROWCOUNT AS loaded;
END;