-- 메뉴 테이블 구조 및 데이터 확인

-- 1. C0007000(타시스템 I/F & Upload) 하위 메뉴 확인
SELECT 
    SR.SYS_RESOURCE_ID,
    SR.UPPER_SYS_RESOURCE_ID,
    SR.SYS_RESOURCE_NAME,
    SR.URL,
    SR.SEQ,
    SR.DEL_YN
FROM DOI_CM_SYS_RESOURCE SR
WHERE SR.UPPER_SYS_RESOURCE_ID = 'C0007000'
ORDER BY SR.SEQ;

-- 2. DOI_CM_SYS_RESOURCE 테이블 컬럼 확인
SELECT TOP 1 * FROM DOI_CM_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'C0007003';

-- 3. C0009001 메뉴가 이미 있는지 확인
SELECT * FROM DOI_CM_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'C0009001';
