-- 202507월 데이터를 202510월로 복사
-- 사업장: HQ
-- 생성일: 2025-11-14

USE 도우제조MES시스템TEST;
GO

PRINT '========================================';
PRINT '202507 → 202510 데이터 복사 시작';
PRINT '사업장: HQ';
PRINT '========================================';
PRINT '';

-- 1. DOI_ACCT (원가계정정보) 복사
PRINT '1. DOI_ACCT (원가계정정보) 복사 중...';
DELETE FROM DOI_ACCT WHERE YYYYMM = '202510' AND SITE = 'HQ';

INSERT INTO DOI_ACCT (YYYYMM, SITE, SEL_CODE, ACCT_CODE, 구분, ACCT_NAME)
SELECT '202510', SITE, SEL_CODE, ACCT_CODE, 구분, ACCT_NAME
FROM DOI_ACCT
WHERE YYYYMM = '202507' AND SITE = 'HQ';

PRINT '   → ' + CAST(@@ROWCOUNT AS VARCHAR) + '건 복사 완료';
PRINT '';

-- 2. DOI_DEPT (부서정보) 복사
PRINT '2. DOI_DEPT (부서정보) 복사 중...';
DELETE FROM DOI_DEPT WHERE YYYYMM = '202510' AND SITE = 'HQ';

INSERT INTO DOI_DEPT (YYYYMM, SITE, SEL_CODE, DEPT_CODE, DEPT_NAME, 구분)
SELECT '202510', SITE, SEL_CODE, DEPT_CODE, DEPT_NAME, 구분
FROM DOI_DEPT
WHERE YYYYMM = '202507' AND SITE = 'HQ';

PRINT '   → ' + CAST(@@ROWCOUNT AS VARCHAR) + '건 복사 완료';
PRINT '';

-- 3. DOI_DEPT_COST (부서별,계정별 투입비용) 복사
PRINT '3. DOI_DEPT_COST (부서별,계정별 투입비용) 복사 중...';
DELETE FROM DOI_DEPT_COST WHERE YYYYMM = '202510' AND SITE = 'HQ';

INSERT INTO DOI_DEPT_COST (
    YYYYMM, SITE, SEL_CODE, DEPT_CODE, ACCT_CODE, 
    DEPT_NAME, ACCT_NAME, AMT, 구분
)
SELECT 
    '202510', SITE, SEL_CODE, DEPT_CODE, ACCT_CODE,
    DEPT_NAME, ACCT_NAME, AMT, 구분
FROM DOI_DEPT_COST
WHERE YYYYMM = '202507' AND SITE = 'HQ';

PRINT '   → ' + CAST(@@ROWCOUNT AS VARCHAR) + '건 복사 완료';
PRINT '';

-- 4. DOI_MODEL_MAST (면적정보) 복사
PRINT '4. DOI_MODEL_MAST (면적정보) 복사 중...';
DELETE FROM DOI_MODEL_MAST WHERE YYYYMM = '202510' AND SITE = 'HQ';

INSERT INTO DOI_MODEL_MAST (
    YYYYMM, SITE, SEL_CODE, MODEL, 구분, AREA
)
SELECT 
    '202510', SITE, SEL_CODE, MODEL, 구분, AREA
FROM DOI_MODEL_MAST
WHERE YYYYMM = '202507' AND SITE = 'HQ';

PRINT '   → ' + CAST(@@ROWCOUNT AS VARCHAR) + '건 복사 완료';
PRINT '';

-- 5. DOI_CASSETTE_RESC (카세트 발생비용) 복사
PRINT '5. DOI_CASSETTE_RESC (카세트 발생비용) 복사 중...';
DELETE FROM DOI_CASSETTE_RESC WHERE YYYYMM = '202510' AND SITE = 'HQ';

INSERT INTO DOI_CASSETTE_RESC (
    YYYYMM, SITE, SEL_CODE, MODEL, 구분, 
    CASS_MAKER, CASS_GUBUN, CASS_QTY, CASS_COST
)
SELECT 
    '202510', SITE, SEL_CODE, MODEL, 구분,
    CASS_MAKER, CASS_GUBUN, CASS_QTY, CASS_COST
FROM DOI_CASSETTE_RESC
WHERE YYYYMM = '202507' AND SITE = 'HQ';

PRINT '   → ' + CAST(@@ROWCOUNT AS VARCHAR) + '건 복사 완료';
PRINT '';

PRINT '========================================';
PRINT '데이터 복사 완료!';
PRINT '========================================';
GO

-- 복사 결과 확인
PRINT '';
PRINT '========================================';
PRINT '복사 결과 확인';
PRINT '========================================';

SELECT '1. DOI_ACCT' AS 테이블, COUNT(*) AS 건수
FROM DOI_ACCT WHERE YYYYMM = '202510' AND SITE = 'HQ'
UNION ALL
SELECT '2. DOI_DEPT', COUNT(*)
FROM DOI_DEPT WHERE YYYYMM = '202510' AND SITE = 'HQ'
UNION ALL
SELECT '3. DOI_DEPT_COST', COUNT(*)
FROM DOI_DEPT_COST WHERE YYYYMM = '202510' AND SITE = 'HQ'
UNION ALL
SELECT '4. DOI_MODEL_MAST', COUNT(*)
FROM DOI_MODEL_MAST WHERE YYYYMM = '202510' AND SITE = 'HQ'
UNION ALL
SELECT '5. DOI_CASSETTE_RESC', COUNT(*)
FROM DOI_CASSETTE_RESC WHERE YYYYMM = '202510' AND SITE = 'HQ';

PRINT '';
PRINT '완료!';
