-- 실제 데이터베이스의 메뉴 관련 테이블 찾기
-- DB명: 도우제조MES시스템DB
-- 스키마: dbo

-- 1. 'RESOURCE' 또는 'MENU'가 포함된 테이블 찾기
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE (TABLE_NAME LIKE '%RESOURCE%' OR TABLE_NAME LIKE '%MENU%')
  AND TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME;

-- 2. 'SYS'로 시작하는 테이블 찾기
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE 'SYS%'
  AND TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME;

-- 3. 'CM'이 포함된 테이블 찾기
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%CM%'
  AND TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME;

-- 4. 'DOI'로 시작하는 테이블 찾기
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE 'DOI%'
  AND TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME;

-- 5. C0007003(생산정보) 관련 데이터가 있을 만한 테이블 찾기
-- 모든 테이블 목록 보기
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME;
